### ISSUE TITLE
Real-Time features

### ISSUE THREAD

**Issue by jonathan-casarrubias** [strongloop/loopback-next#119]
# Description/Steps to reproduce

I'm opening this thread to discuss and define a scope for real-time functionalities possibly provided by LB-Next.

Currently there are implemented functionalities like event streams, but honestly are not helpful at all when building real life applications, therefore I have built several real-time approaches on top of loopback, which I believe 2 were the most important.

1.- Implemented PubSub functionality.
2.- Implemented Firebase alike interface.

I want to start the conversation because I know from @ritch expects to provide better RT Interface(s), I will talk about my experiences by sharing the pros and cons I consider from these approaches.

### Pros

- Small learning curve
- Easy to subscribe to CUD methods
- Does't require a complex client sdk (for instance can subscribe using plain socket.io)
- Lighter in terms of processes
- Easier to implement
- Easier to scale

### Cons

- If hooking from REST calls, triggers won't fire when using LoopBack's NodeJS API
- Requires HTTP Calls to trigger WS Event, unless we provide the exact same REST Api but using WS Events instead
- Is too coupled to the REST API

*NOTE: Sails.js out of the box offers PubSub events to be subscribed from any REST Endpoint*

### Pros

- Similar to ORM in the back-end but for realtime communications from the front-end
- Does't depend on any REST interface at all, is more model oriented (like real-time ORM)
- Richest interface of communication, allows different behaviour and not just subscribing to latest event change
- Allows to build more complex real-time applications by allowing every subscriber to receive filtered data (Every client receives their custom requested data, is not generic to everyone)

### Cons

- Higher learning curve
- Requires to provide complex client sdks (Will be difficult to provide different clients for different languages)
- Managing subscriptions is harder and more difficult to scale since every request from different clients might be different for the exact same event (Example in paginated lists)
- Can be heavier in terms of processes
- Is more difficult to scale while attending unique client requests for same event

That is all I can think for now, but is only to start the conversation... There might be more cons and pros from these 2 approaches I already offer while using the modules I maintain.

Looking forward to see what your plans are on RT Features.

Cheers
Jon

**Comment by Brian-McBride** [comment]
There is an interesting server/tech called `[deepstream.io](http://deepstream.io)`  that is a real-time server that in opinionated to the database it connects to.

Their license is going to preclude it from working with Loopback I suspect - however if you look at their core server source it is node.js based. 

With some elbow grease, someone could hook the two together, perhaps through a dataconnector and listeners to the deepstream events. There would be some work unifying auth and the roles engine so that they align in an easy way too.

**Comment by kjdelisle** [comment]
I like this idea, but I think it's probably best implemented as a component rather than a part of the core offerings of loopback-next. Our intent will be to release beta soon(ish), and attempt to keep the component APIs stable so that developers can get a head start on creating their own components.

@raymondfeng @bajtos @virkt25 thoughts?

**Comment by bajtos** [comment]
+1 for implementing this as a component/extension. However, we should ensure that our core is flexible and extensible enough to make this extension easy to build.

**Comment by jskrzypek** [comment]
Fwiw, it might be worth looking at [feathers](https://feathersjs.com). They also have an opinionated model of realtime eventing backing standard CUD operations, like deepstream.io, but they're entirely OSS, I believe. 

They have some overlap in functionality with the goals of loopback, providing a pretty basic, if extensible ORM with various database connectors, but like loopback-next they have also recently decoupled from express, and it's entirely possible to run feathers purely as a realtime/socket server.

I would certainly love to see and would also be interested in contributing to an extension/connector that could bridge the gap between them.

**Comment by kattsushi** [comment]
@jskrzypek i would like to collaborate in this feature from beginning with an extension that provides feat to some controller or method in loopback-next maybe with Socket.io or WebSocket, im trying to figure out yet how works, but already i started working on it here https://github.com/kattsushi/loopback4-extension-socketio based in loopback4-extension-grpc  @jonathan-casarrubias has working in this one and he has a broader vision about the extensions, and it seemed like a good starting point

**Comment by collaorodrigo7** [comment]
Have you guys started some work on this? I am not an expert, but I would truly like to help

**Comment by jannyHou** [comment]
hi @collaorodrigo7 thank you for being interested in adding real-time features in LoopBack 4!
Recently the team is focusing on several fundamental epics, like cloud native, new boot module, new relation, http server refactor, etc... We haven't work on the real-time functionalities and appreciate your help.

Maybe we can start with describing our targets:
Based on the discussion above, any specific feature(s) you would like to implement?

Here are some references may help you:

LB4 provides a default rest server to process HTTP requests, see [concept server](https://loopback.io/doc/en/lb4/Server.html), it also talks about how to customize the sequences and actions to modify the default behaviour.

User can also create their own server, see [creating server](https://loopback.io/doc/en/lb4/Creating-servers.html)

To get familiar with contributing extensions in LoopBack4, we have an example repo that demos various approaches to extend the framework: 
https://github.com/strongloop/loopback-next/tree/master/examples/log-extension
And the doc [creating components](https://loopback.io/doc/en/lb4/Creating-components.html)

**Comment by collaorodrigo7** [comment]
Thanks for the references @jannyHou.
I was reading at the posts and the options mentioned before on the discussion as [feathers](https://feathersjs.com/) and [deepstream](https://deepstreamhub.com/open-source/?io)
All pretty interesting
While looking at them I run into [gun.eco](https://gun.eco/) (they call themselves self-hosted firebase),which called my attention because it is/has (according to their docs):

- Realtime updates
- Distributed (peer to peer by design)
- Offline first
- Graph database

Now, I am not sure if that will be something you guys want or think that will be good to have on lb4 or will be in the scope of the project. I am not sure but I don't think we have connectors for graph databases, do we?

Answering your question, I would like to implement the real-time updates keeping in mind offline capabilities. 

Please consider it is my first time contributing to an open source project, so I have no previous experience, but I will try my best.

**Comment by matejthetree** [comment]
any updates on socket implementation in lb4?

**Comment by virkt25** [comment]
@matejthetree It's not part of the current scope of work we're doing for General Availability (GA) of the framework. Most likely it will be after that unless you would be interested in helping out by implementing it? The team would be more than happy to help you in any way we can along the way.

**Comment by matejthetree** [comment]
I was thinking of creating just my own socket server and router(like rpc example). How different is this from creating an extension for socket.io

If it is not a huge scope, I would be happy to do it.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/issues/1884
