### ISSUE TITLE
[CLI] Generate model

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1221]
## Description / Feature proposal
CLI command to generate model TS file. 
- The prompt asks:
   - name of the model
   - property name and type (repeating till user enter empty name for property name)
- The generated model.ts would look something like: https://github.com/strongloop/loopback-next/blob/0411811aa8348e31636fb0fe07b44dd18469280f/examples/todo/src/models/todo.model.ts

### Outstanding questions
- Do we ask the user to select the base class?  If yes, what are the selections? or it will always be `Entity`.
- What are the property types we support? Here is what we have in LB3:
string 
  number 
  boolean 
  object 
  array 
  date 
  buffer

## Acceptance Criteria
- [x] Make a CLI prompt for model and its properties
  - [x] For properties, ask for their name, their types and their default values
- [x] The produced model should extend from `Entity`

### User Experience
```
$ lb4 model
? Enter the model name: Customer
Let's add some Customer properties now. 

Enter an empty property name when done.
? Property name: customerId
? Property type:  (show a list of available types) string
? Required? (y/N) y
? Default value[leave blank for none]:

Let's add another Customer property.
Enter an empty property name when done.
? Property name: name
? Property type:  (show a list of available types) string
? Required? (y/N) y
? Default value[leave blank for none]:

```
At the end, `src/models/customer.model.ts` will be created.

**Comment by bajtos** [comment]
> Do we ask the user to select the base class? If yes, what are the selections? or it will always be Entity.

For DP3, I think it's ok to always use `Entity` as the base class.

> What are the property types we support? Here is what we have in LB3:
string
number
boolean
object
array
date
buffer

I think that list is a good start and enough for DP3. However, the arrays should be typed. When the user selects "array", we should ask them to provide the type of array items (e.g. "string" or "number" - basically anything from the list above with the exception of arrays).

**Comment by dhmlau** [comment]
related to https://github.com/strongloop/loopback-next/issues/441

**Comment by bajtos** [comment]
> Rejecting because we do not have information on how the models will interact with the potential artifacts being created (e.g. JSON representations)

In the current design (at least for DP3 scope), models are defined code-first by using TypeScript classes and annotations, see e.g. [examples/todo/src/models/todo.model.ts](https://github.com/strongloop/loopback-next/blob/0411811aa8348e31636fb0fe07b44dd18469280f/examples/todo/src/models/todo.model.ts).

As I understand the goal of this story, we need a CLI command that will create a `.model.ts` files and a `.repository.ts` file based on user input.

A story to tell: as a user creating `examples/todo` application, I don't want to manually create model & repository files because I don't remember what are the conventions. Instead, I'd like to run a command like `lb4 model` that will prompt for necessary data and create the files for me.

The repository requires a datasource to be attached to. The CLI should scan `datasources` folder (see [examples/todo/src/datasources](https://github.com/strongloop/loopback-next/tree/0411811aa8348e31636fb0fe07b44dd18469280f/examples/todo/src/datasources)).

Remember, we are not trying to build the ideal solution that won't need any further changes. Instead, we want to simplify the process of building `examples/todo` app by providing CLI tooling that produces artifacts following the current app design.

If we decide to change the app design guidelines, e.g. by moving datasource config from TypeScript to JSON, then such task would require an update of `lb4 model` command. That's out of scope of the task of creating the initial version of `lb4 model` though!

**Comment by dhmlau** [comment]
@virkt25 , assigning this to you, because you're doing this as part of the spike #441 already. thanks.

**Comment by dhmlau** [comment]
@virkt25 , if it's good for estimate, please move to the `needs estimate` column.  thanks.
