### ISSUE TITLE
[CLI] Model epic

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1339]
## Description / Steps to reproduce / Feature proposal

An epic to organize all things CLI model generation

### Create a command with a set of prompts for a model
- #1221 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Cross-posting from https://github.com/strongloop/loopback-next/issues/1221#issuecomment-390253696:

In the current design (at least for DP3 scope), models are defined code-first by using TypeScript classes and annotations, see e.g. [examples/todo/src/models/todo.model.ts](https://github.com/strongloop/loopback-next/blob/0411811aa8348e31636fb0fe07b44dd18469280f/examples/todo/src/models/todo.model.ts).

As I understand the goal of this story, we need a CLI command that will create a `.model.ts` files and a `.repository.ts` file based on user input.

A story to tell: as a user creating `examples/todo` application, I don't want to manually create model & repository files because I don't remember what are the conventions. Instead, I'd like to run a command like `lb4 model` that will prompt for necessary data and create the files for me.

The repository requires a datasource to be attached to. The CLI should scan `datasources` folder (see [examples/todo/src/datasources](https://github.com/strongloop/loopback-next/tree/0411811aa8348e31636fb0fe07b44dd18469280f/examples/todo/src/datasources)).

Remember, we are not trying to build the ideal solution that won't need any further changes. Instead, we want to simplify the process of building `examples/todo` app by providing CLI tooling that produces artifacts following the current app design.

If we decide to change the app design guidelines, e.g. by moving datasource config from TypeScript to JSON, then such task would require an update of `lb4 model` command. That's out of scope of the task of creating the initial version of `lb4 model` though! (And very likely out of DP3 scope too.)
