### ISSUE TITLE
[CLI][SPIKE] Generate an app by passing in a config file

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1341]
## Description / Steps to reproduce / Feature proposal

In order to enable external CLI/GUI tooling to scaffold and possibly edit LoopBack applications, we need to implement a non-interactive mode for our generators.

Ideally, the CLI should accept a single JSON file containing instructions on what command to execute (app, model, etc.) together with any answers needed by those commands (app name, model name, etc.).

## Discussion points
- What is the file format for the config file?
- What properties/options are we going to give to the users?
- What is the UX of the experience going to look like?

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by jannyHou** [comment]
Hi @shimks , do you mean when create an app from cli, there is only one prompt asking for a config file, user specify the file path then the app get scaffolded?

**Comment by dhmlau** [comment]
Also, I'd like to propose this as either `DP3` `p2` or `non-DP3`. 
@raymondfeng @bajtos , what do you think?

**Comment by bajtos** [comment]
I am not sure what's the intent of this particular story since I am not the author, but: recently we were discussing how to better integrate LoopBack generators with the tooling provided by our runtime team. The discussion boiled down to a requirement that an external CLI/GUI tool should be able to scaffold a LoopBack application with multiple artifacts (models, etc.) in a single non-interactive call of our CLI. The external CLI/GUI tool will provide answers to all required prompts in a JSON file and then pass that JSON file to us to execute.

**Comment by bajtos** [comment]
IMO, this is non-DP3, but it would be great to have it as part of Core GA.

**Comment by shimks** [comment]
I may have misunderstood the main points of the topic during the aforementioned discussion. Since my main intent was to capture the information from that discussion, please feel free to edit the description so that it more accurately reflects the discussion that have taken place

**Comment by bajtos** [comment]
Done. I have also changed this story into a spike.

**Comment by dhmlau** [comment]
Closing it as done.
