### ISSUE TITLE
Infer target repository when related models are backed by the same datasource

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1353]
## Description / Steps to reproduce / Feature proposal
Infer target repository when related models are backed by the same datasource, otherwise let user explicitly provide the target repository.
See https://github.com/strongloop/loopback-next/pull/1194#issuecomment-384626282

> > If use 3 to provide relational access, the customer instance needs to have a pointer to CustomerRepository as well as OrderRepository. It can be achieved to make customer a managed instance of the context/repositories or make customer.orders a factory of relational access, such as customer.orders(orderRepository).*.
> 
> I see two use cases:
> 
> Use case 1: Both related models are backed by the same datasource and using the same CRUD repository API. In this case, the repository implementation (DefaultCrudRepository) for the source model (Customer) has all information needed to create a repository implementation for the target model (Order). There is no need for the user to explicitly provide the target repository.
> 
> A mock-up:
> 
> ```ts
> class DefaultCrudRepository<T extends Entity, ID> {
>   // ...
> 
>   getRepositoryForModel<R extends Entity, RID>(targetModelCtor: typeof Entity & {prototype: R}) {
>     const dataSource = this.modelClass.dataSource;
>     return new DefaultCrudRepository<R, RID>(targetModelCtor, dataSource);
>   }
> }
> ```
> 
> Use case 2: Each related model is backed by a different datasource and/or use different Repository API. In this case, the navigational method requires the caller to provide the target repository instance. I expect the callers to obtain the reference of the target repository via dependency injection.

### Acceptance Criteria
- [ ] Introduce `getRepositoryForModel()` function inside `DefaultCrudRepository` class as shown in the code snippet above 
- [ ] Write tests/docs for it (need to tell users that this is not applicable if they're not using the same datasource for their related models).

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by b-admike** [comment]
@bajtos could you please add some acceptance criteria for this task?

**Comment by bajtos** [comment]
@b-admike sure. Here is what I would like to see - please let me know if it's aligned with your vision for releations too.

Right now, a controller method exposing a relation method looks like this:

https://github.com/strongloop/loopback-next/blob/2783acf02880eadbb056aa1756e428c3c40c824d/packages/repository/test/acceptance/has-many.relation.acceptance.ts#L36-L49

The goal of this story is to allow controllers to access the related repository directly as follows (assuming both models are backed by the same datasource):

```ts
async function create(customerId: number, orderData: Partial<Order>) {
  return customerRepo.orders().create(customerId, orderData);
}
```

By defining `orders()` as a method (not a property), we leave the doors open to add optional arguments in the future, for example to allow callers to provide a different datasource. That's out of scope of this issue though.

@raymondfeng what's you opinion, is this aligned with your vision for relations?

A short note on what's said in issue description:

> the navigational method requires the caller to provide the target repository instance. I expect the callers to obtain the reference of the target repository via dependency injection.

I don't think it's a good design to require controllers to understand which datasources are used to back which models. In my view, datasources are an implementation detail (a configuration) of repositories that should not leak out to other parts of the application like controllers. What I would like to see instead: the `customerRepo` injected to the controller should be already configured to use the right datasource to access related orders. The injection of the other datasource should happen at CustomerRepository creation.

Having said that, I think it's still a good idea to keep our options open and access related repositories via a method, so that it's possible to implement injection inside controllers if we find good justification for that.

**Comment by bajtos** [comment]
See also https://github.com/strongloop/loopback-next/issues/1372, I think these two stories are rather intertwined.

**Comment by raymondfeng** [comment]
Here is my take:

1. `customerRepo.orders` should be a factory method to get an instance of `OrderRepository` which will enforce the FK referential integrity 
2. The decoration of `orders` property should have enough metadata to help our runtime to know which target repository to use. For example:
```ts
export class CustomerRepository {

  @relation({targetRepository: ...}) // We can infer the targetRepository if not provided
  public orders: (...) => OrderRepository; // `orders` should match the relation definition for `Customer` unless it's customized in the decorator
}
```
3. `customerRepo.orders()` should take the constraint such as `{id: 'customer0001'}` as an argument:
```ts
const orders = await customerRepo.orders({id: 'customer0001'}).find(...);
```

**Comment by b-admike** [comment]
I agree with having the factory method on the repository instance (which I think we all agree on). IMO, decorating the factory method and inferring the target repository from it makes sense. My question is how we should, in a high level, infer the target repository if the models are backed by the same datasource this way. I think if we can settle on the first incremental feature for this task, then we can build on top of it.

>I don't think it's a good design to require controllers to understand which datasources are used to back which models. In my view, datasources are an implementation detail (a configuration) of repositories that should not leak out to other parts of the application like controllers. What I would like to see instead: the customerRepo injected to the controller should be already configured to use the right datasource to access related orders. The injection of the other datasource should happen at CustomerRepository creation.

Agreed, but I think it goes against the following part of your comment, no?
>By defining orders() as a method (not a property), we leave the doors open to add optional arguments in the future, for example to allow callers to provide a different datasource. That's out of scope of this issue though.

@raymondfeng can you please clarify this comment?
> // `orders` should match the relation definition for `Customer` unless it's customized in the decorator

**Comment by bajtos** [comment]
> customerRepo.orders should be a factory method to get an instance of OrderRepository which will enforce the FK referential integrity

I fully agree with the first part: " customerRepo.orders should be a factory method to get an instance of a repository".

I disagree with the idea that a relational repository should be the same as DefaultCrudRepository. Relations don't have the same API as regular repositories, for example `execute` is difficult to impossible to implement for HasMany relation, HasAndBelongsToMany relations needs to expose additional APIs like `link` and `unlink` on top of the usual CRUD repository.

My proposal:

_customerRepo.orders should be a factory method to get an instance of `HasManyRepository<Order>` which will enforce the FK referential integrity_

>  Agreed, but I think it goes against the following part of your comment, no?

Well, I cannot fully envision how the integration with controllers is going to look like. By making `_customerRepo.orders` a method, we have the option to add additional arguments in the future. If it turns out it's not feasible to inject or infer the target repository for the relation model and callers for `_customerRepo.orders` must provide it, then if `orders` was a getter property, we would have hard times. On the other hand, if `orders` is a method and we don't need to add any arguments (yet), because the target repository for the relation model will be provided by the caller of `_customerRepo` constructor or in `@relation` decorator, then nothing wrong happened.

Anyhow, I think this is sort of moot anyways because we agreed that the FK constraint should be passed to `_customerRepo.orders` and not to individual methods of orders repository, therefore `_customerRepo.orders` must be a method anyways.

> My question is how we should, in a high level, infer the target repository if the models are backed by the same datasource this way. I think if we can settle on the first incremental feature for this task, then we can build on top of it.

As a user, I would like my `CustomerRepository` to have `orders()` method created for me by the framework. Here is a mock-up implementation I am envisioning:

```ts
class CustomerRepository extends ... {
  orders(scope) {
    return new DefaultHasManyCrudRepository<...>(Order, this.dataSource, scope);
  }
}
```

Now the question is - how is the `orders` method going to be created? One option is to let our CLI tooling to define this methods, but then CLI tooling for relations is out of scope of DP3. We can try to implement a mixin that will add such method, but I am not sure about the complexity of such solution, it may not be worth the benefits.

Maybe it's enough to implement a protected helper method in `DefaultCrudRepository` class as outlined in the issue description at the top (see `getRepositoryForModel`) and tell users to manually write `orders()` method deferring to `getRepositoryForModel` under the hood? Except we cannot use a single `getRepositoryForModel`, but need `getHasManyRepositoryForModel`, `getBelongsToRepositoryForModel`, etc.

I am not sure to be honest.

**Comment by b-admike** [comment]
>I disagree with the idea that a relational repository should be the same as DefaultCrudRepository. Relations don't have the same API as regular repositories, for example execute is difficult to impossible to implement for HasMany relation, HasAndBelongsToMany relations needs to expose additional APIs like link and unlink on top of the usual CRUD repository.

>My proposal:

>customerRepo.orders should be a factory method to get an instance of HasManyRepository<Order> which will enforce the FK referential integrity

Yeah that makes sense to me 👍. 

>On the other hand, if orders is a method and we don't need to add any arguments (yet), because the target repository for the relation model will be provided by the caller of _customerRepo constructor or in @relation decorator, then nothing wrong happened.

I like this approach, and like you said it is moot point as we agreed to pass in the FK constraint to it.

>Now the question is - how is the orders method going to be created?

Yes I think that was my root concern now that I think about it.

>Maybe it's enough to implement a protected helper method in DefaultCrudRepository class as outlined in the issue description at the top (see getRepositoryForModel) and tell users to manually write orders() method deferring to getRepositoryForModel under the hood? Except we cannot use a single getRepositoryForModel, but need getHasManyRepositoryForModel, getBelongsToRepositoryForModel, etc.

I also don't really have any suggestions, but your proposal sounds good to me. As we work on #1372, it might become more clear what to do here or the alternatives.

**Comment by shimks** [comment]
@b-admike Can you make a quick summary of the discussion that has taken place in this issue in the acceptance criteria? Thanks

**Comment by b-admike** [comment]
Sorry it's been a while. I'll take a look at this and try to summarize the discussion this week.

**Comment by dhmlau** [comment]
@b-admike ping ^^^

**Comment by b-admike** [comment]
@bajtos @raymondfeng Discussion point: how do we make sure users do not accidentally call the `getRepositoryForModel()` function as specified in https://github.com/strongloop/loopback-next/issues/1353#issue-326177717 when they're using different datasources for their related models? In terms of UX, is there really a big advantage of using this function instead of DI as we do currently? The rest of the items discussed in this thread are already resolved IMO.

**Comment by bajtos** [comment]
Here is my understanding of the current implementation:
 - A CRUD repository (e.g. [TodoListRepository](https://github.com/strongloop/loopback-next/blob/ec37f2fe90f9cda7802d6adcd9632ce8d1516c59/examples/todo-list/src/repositories/todo-list.repository.ts#L22-L31)) provides a method (a property returning a function) for obtaining a relation repository instance, e.g. `todoListRepo.orders(listId)`.
- This function property is initialized by CRUD repository constructor, using a helper method `_createHasManyRepositoryFactoryFor`.
- `_createHasManyRepositoryFactoryFor` requires a repository instance for accessing the target model. This is different from what has been discussed in this issue, where we were assuming it will be the datasource instead of the repository.

Based on this understanding, I think the original goal of this issue should be rephrased as follows:

As a developer building a repository for a model (Customer) that has a relation to another model (Order), where both models are backed by the same datasource, I'd like `_createHasManyRepositoryFactoryFor` to infer the datasource AND the repository for the target model, so that I can simplify the implementation of my repository as shown on the example below. I think we should keep the previously mentioned method `getRepositoryForModel` as an implementation detail, possibly exposed as a protected method for future extensibility.

```ts
export class TodoListRepository extends DefaultCrudRepository<
  TodoList,
  typeof TodoList.prototype.id
> {
  public todos: HasManyRepositoryFactory<Todo, typeof TodoList.prototype.id>;

  constructor(
    @inject('datasources.db') protected datasource: juggler.DataSource,
  ) {
    super(TodoList, datasource);
    this.todos = this._createHasManyRepositoryFactoryFor('todos');
  }
}
```

Coming back to this topic after a while, I am no longer convinced this shorthand version is desirable. 

My main concern is about using `DefaultHasManyCrudRepository` as the only hardcoded repository implementation used in the default mode. In a typical LB4 app scaffolded by our tooling, there will be a custom repository class provided for the target model (e.g. `OrderRepository`). Users may use inheritance and method overriding to customize the behavior of certain repository methods, for example modify `find` to add `{deleted: false}` condition to all queries. If the developer leaves `_createHasManyRepositoryFactoryFor` to use the default crud repository implementation, then they end up with a broken application: direct queries for Orders will hide deleted orders, queries for customer orders will show deleted orders.

I think this is mostly the same concern as expressed by @b-admike above:
> how do we make sure users do not accidentally call the getRepositoryForModel() function as specified in #1353 (comment) when they're using different datasources for their related models? In terms of UX, is there really a big advantage of using this function instead of DI as we do currently?

My conclusion: close this issue as no longer relevant. We can always come back to this discussion if there is enough user feedback or demand for it.

**Comment by bajtos** [comment]
I am closing this issue per my comment above. @raymondfeng @b-admike feel free to reopen if you disagree.
