### ISSUE TITLE
Object-level ACL's

### ISSUE THREAD

**Issue by jesperbruunhansen** [strongloop/loopback-next#141]
I would like to see an even more advanced ACL implementation in Loopback.next, that supports ACL's on a object-level.

LB v.2/3 has great ways of applying ACL's to an entire model and it's methods, but in many use-cases I want objects/instances only to be accessible to specific users, which has been explicitly granted permission by the client upon creation (pending issue at Loopback repo [here](https://github.com/strongloop/loopback/issues/1427)).

When the client requests an authenticated `GET` request, the response will only contain objects that the client has permission to read. 

I've made my own [mixin](https://github.com/jesperbruunhansen/loopback-object-acl) to add this feature, which basically manipulates the query at every 'access' event of the datasource.

I'd be happy to help implement this feature into native Loopback.next, should it be considered beneficial for the framework.

**Comment by jcurlier** [comment]
+1

**Comment by bajtos** [comment]
Hi @jesperbruunhansen, thank you for opening this issue. Object/instance-level ACLs make a lot of sense to me. I think this is one of the reasons we decided for a complete rewrite in loopback.next - adding generic object/instance-level ACLs was simply too difficult in the old codebase.

@ritch @raymondfeng @superkhau what's your opinion?

> I'd be happy to help implement this feature into native Loopback.next, should it be considered beneficial for the framework.

Offer accepted :)

Right now, we are trying to figure out how to design LoopBack.next in such way that ACL checks like the one you are described can be easily contributed by components/plugins, it's probably too early to start the actual work on implementing such component.

**Comment by jesperbruunhansen** [comment]
Hi @bajtos, and thank you for your explanation.

> it's probably too early to start the actual work on implementing such component.

Sure of course, let me know when the time is right and I'll see where I can help!

**Comment by superkhau** [comment]
@bajtos 100% agree with Object/instance ACLs and even model property ACLs.

**Comment by kesavkolla** [comment]
If you're doing ACL support at object level then extend it to field level also.  Similar to Salesforce data model where users have ability to define roles to field levels too.

**Comment by RomanovRoman** [comment]
I think about it in several projects. And...
**IMHO it is a really bad idea for RESTfull api.**
Because we must have fast token-based ACL mechanics for endpoints.
May be we needs in more featured [dynamic-roles](http://loopback.io/doc/en/lb3/Defining-and-using-roles.html#dynamic-roles) and [nestRemoting](http://loopback.io/doc/en/lb3/Nested-queries.html)?
I think we should to consider several concrete real-world use cases in REST and GraphQL in this discussion.

**Comment by superkhau** [comment]
>I think we should to consider several concrete real-world use cases in REST and GraphQL in this discussion.

+1 for more real-world use cases in both REST and GraphQL. I would like to hear more about why it is really a bad idea for RESTful APIs.

**Comment by RomanovRoman** [comment]
> I would like to hear more about why it is really a bad idea for RESTful APIs.

Every URI like: `http://domain.tld/api/entity` represents concrete collection of concrete entities and users should have  from GET request:
- **the same JSON** with 2xx status
- some response without any entities (4xx, 3xx and so on)

It is about proxy and cache.
For example, browser wants to `GET http://domain.tld/api/entity` then nginx-proxy can ping our api server with `HEAD http://domain.tld/api/entity` request and send response to browser from disk cache without rendering new JSON by api server.
That's why we should use [nestRemoting](http://loopback.io/doc/en/lb3/Nested-queries.html) and make endpoints like `http://domain.tld/api/user/id/entity` and `http://domain.tld/api/group/gid/member/mid/entity`

On the other hand, we needs in **javascript**ed read/write permissions on client with minimal DB requests. IMHO it is not good practice to send unnecessary (unwanted) requests which will be rejected by api server. Full ACL-set request will generate unwanted http-traffic.

PS
Javascript is pretty language which makes possible to use several programming paradigms in the same time and place (file). But in APIs we deal with entities (REST, DB, node-modules, etc) therefore we must thinking in OOP-style only. It makes architecture more clear and understandable by human beings.

**Comment by raymondfeng** [comment]
ACL should be enforced at different tiers based on how much knowledge we acquire about the request (who wants to do what). For APIs, I see the following:

1. API gateway with oAuth2 to protect endpoints against scopes
2. Route based ACL - See https://github.com/strongloop-community/loopback-acl-route
3. Implementation level ACL for controller/repository
4. Backend (downstream) ACL

**Comment by jesperbruunhansen** [comment]
Hi guys, and thanks for nice discussion regarding this issue.

> +1 for more real-world use cases in both REST and GraphQL

My inspiration and need for this feature comes from the time when I worked on a project, using the [Parse-server ](https://github.com/parse-community/parse-server). When they open-sourced, I basically copied what they did [here](https://github.com/parse-community/parse-server/blob/b6298feaa7124608a843b988164a4372b9900dc0/src/Controllers/DatabaseController.js#L11-#L23) in order to make the same functionality in Loopback. 

Their overall approach to ACL's can be seen [here](http://docs.parseplatform.org/js/guide/#clp-and-acl-interaction), whereas I like to compare Loopbacks current ACL implementation as the "Class-level" ACL's of Parse.

I like the idea of even more granularity with field-level ACL's as well, as @superkhau and @kesavkolla mentioned.

**Comment by raymondfeng** [comment]
@jesperbruunhansen I'm with you.  Coincidentally, I have been thinking about the possibility to mix conditions into the `filter` to enforce property level ACLs.

**Comment by RomanovRoman** [comment]
@raymondfeng instead of property level ACLs...
It would be nice to introduce [Data Transfer Object](https://martinfowler.com/eaaCatalog/dataTransferObject.html)s for each triplet(method, resource, role).
Then **DTO**s will define full fieldset for each remote method and will aggregate serialization, parse(deserialization), validation logic which is the same for both client and server.

**Comment by virkt25** [comment]
not stale. post-MVP

**Comment by dhmlau** [comment]
This involves ACL at the controller level and data level.
