### ISSUE TITLE
Update Todo tutorial to load datasources via loopback boot

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1440]
## Description / Steps to reproduce / Feature proposal

The pull request https://github.com/strongloop/loopback-next/pull/1385 simplified `examples/todo` application to leverage `@loopback/boot` capability of loading datasources from source files.

## Current Behavior

The Todo tutorial shows instructions for the old registration based on a single `config/datasources.json` file.

http://loopback.io/doc/en/lb4/todo-tutorial-datasource.html

## Expected Behavior

The tutorial matches the actual code in `examples/todo` project.

cc @virkt25 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by virkt25** [comment]
Appropriate changes were made in the docs -- see https://github.com/strongloop/loopback-next/blob/master/docs/site/todo-tutorial-datasource.md -- we haven't done a release since the changes so the docs weren't published in a new package and hence not picked up by `loopback.io`. 

Will do a release tomorrow morning to fix this.

**Comment by virkt25** [comment]
New version of `@loopback/docs` was published and `loopback.io` has picked up the latest changes. Closing this as fixed.
