### ISSUE TITLE
No package-lock.json?

### ISSUE THREAD

**Issue by purplemana** [strongloop/loopback-next#1579]
## Description / Steps to reproduce / Feature proposal
Didn't see a lockfile for safe npm installs. Are you tackling it in a different way?

**Comment by virkt25** [comment]
> Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies. -- npm

We've disabled `package-lock.json` **intentionally** as the file is only a development aid and not ever published.

We believe in making sure we know when a dependency breaks us so we can fix it ASAP and disabling the lock file gives us that flexibility (CI/Devs can know) instead of being protected by a `lock` file while users installing a package might be breaking because of a minor / patch release. 

Did you run into any issues with us not having a `package-lock.json` file?

**Comment by purplemana** [comment]
Nope, but while working with a large repos, I have seen too many failed dev installs due to broken third party packages which didn't follow semver as intended. So I was wondering how you guys are solving it.
I do appreciate your strategy. And when you do find an issue with a third party package, do you specify the exact last working version instead of `~`?

**Comment by purplemana** [comment]
Thanks for the detailed response, closing this issue.
