### ISSUE TITLE
SOAP Tutorial LB4 Doc Page Not Found

### ISSUE THREAD

**Issue by binx01** [strongloop/loopback-next#1638]
When browsing SOAP calculator Web Service integration tutorial (https://loopback.io/doc/en/lb4/soap-calculator-tutorial.html) some tutorial subsections don't work for example:

page found when browsing main page: https://loopback.io/doc/en/lb4/soap-calculator-add-datasource.html
page not found when browsing left menu: https://loopback.io/doc/en/lb4/soap-calculator-tutorial-add-datasource.html

Also when browsing main tutorial page, last two steps are not available either:
https://loopback.io/doc/en/lb4/soap-calculator-tutorial-make-service-available.md
https://loopback.io/doc/en/lb4/soap-calculator-run-and-and-test.md

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
@marioestradarosa could you please take a look? I think the sidebar entries should be easy to fix. 

Besides the links not working, I also noticed some tutorial pages are not loading images, see e.g. the [main page from README](https://loopback.io/doc/en/lb4/soap-calculator-tutorial.html) or the step [add datasource](https://loopback.io/doc/en/lb4/soap-calculator-add-datasource.html). I checked the source, you are using a path like `../../docs/img/loopback-example-soap-calculator_figure2.png`. 

I think that's a wrong approach.

For doc pages, just use `../img` at the beginning of the path.

For the image served by README, I think the easiest option is to use a URL pointing to loopback.io, even though it will make it difficult to preview image changes locally. IIRC, we are already using this approach elsewhere. @shimks @virkt25 could you please confirm?

**Comment by bajtos** [comment]
@binx01 thank you for reporting the issue ❤️

**Comment by virkt25** [comment]
> Besides the links not working, I also noticed some tutorial pages are not loading images, see e.g. the main page from README or the step add datasource. I checked the source, you are using a path like ../../docs/img/loopback-example-soap-calculator_figure2.png

The issue here is not only the wrong relative path but also as per my comment https://github.com/strongloop/loopback-next/pull/1639#discussion_r212507311 is that the images are at the wrong location `docs/img` instead of `docs/site/imgs` which gets extracted into the Jekyll site. Here's the script responsible for the extraction: https://github.com/strongloop/loopback.io/blob/gh-pages/update-lb4-docs.js

> For doc pages, just use ../img at the beginning of the path.

In other places in the docs we use  `![loopback-extension](./imgs/loopback-extension.png)`

> For the image served by README, I think the easiest option is to use a URL pointing to loopback.io, even though it will make it difficult to preview image changes locally. IIRC, we are already using this approach elsewhere. @shimks @virkt25 could you please confirm?

Yes, for any `.md` file outside of the `docs/site` folder, such as a `README.md`, the url for the image should be absolute such as `![todo-tutorial-overview](https://loopback.io/pages/en/lb4/imgs/todo-overview.png)`
