### ISSUE TITLE
Datasource creds invalidity should be detected before app starts

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1640]
## Description / Steps to reproduce / Feature proposal

Set up any datasource with invalid creds. App starts fine, but crashes when making requests to the models.

## Current Behavior

App starts successfully but crashes when making requests to resources.

## Expected Behavior

App should not start with invalid creds. This is the behavior in LB3.

## Acceptance Criteria

If datasource creds are invalid, when starting the app:

- [ ] Should report invalid creds
- [ ] App should exit

**Comment by virkt25** [comment]
This requires more discussion and planning around LifeCycle support for a DataSource. There is syntax validation, just reporting error (not crashing) on invalid credentials (lazyConnect is a feature in LB3). Also need to differentiate between failure to connect due to invalid password vs. database being temporarily down, etc. 

Based on discussion with @raymondfeng this is `post-GA` so all the above can be discussed and planned accordingly.
