### ISSUE TITLE
repo.findOne(filter, options) not working as expected with loopback-connector-rest

### ISSUE THREAD

**Issue by payne-chris-r** [strongloop/loopback-next#1707]
## Description / Steps to reproduce / Feature proposal
See for SOME background https://github.com/strongloop/loopback/issues/3999#issuecomment-420419366

We've stepped through the code a bit, and it looks like it's potentially a problem with `qs` not formatting the query string correctly, potentially in `stringify`?

We tried adding an options object:
```js
repo.findOne({where: { prop: val }}, { useQuerystring: true})
```
but that only made our problem "worse" by replacing the `where[prop]=value` to `where=`

Are we missing additional options? Should we not be encoding? Seems like this should be working or is fundamentally broken. Are we certain the `.findOne` works in lb4?

Our datasource looks like this:
```
{
  "name": "datasource",
  "connector": "rest",
  "baseURL": "http://localhost:3020/v1/",
  "crud": false
}
```
We just want to do a simple GET, but it's certainly proving to be difficult...

## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by payne-chris-r** [comment]
FWIW, we also tried `"crud": true`

**Comment by payne-chris-r** [comment]
Is there potentially a bug with `legacy-juggler-bridge`?

**Comment by payne-chris-r** [comment]
Do we need to be defining our controller methods like is shown here?
https://github.com/strongloop/loopback-next/blob/master/docs/site/Repositories.md#defining-crud-methods-for-your-application

**Comment by bajtos** [comment]
@payne-chris-r first of all, could you please create a small application reproducing the issue? Please use loopback-sandbox as described in https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report for the LB 2.x backend, add LB4 front-end via `lb4 app`.

It's difficult for us to troubleshoot an issue we cannot reproduce locally and unfortunately we don't have time to create those apps ourselves.

With that being said: I suspect the problem lies in the way how loopback-connector-rest is building the outgoing HTTP request. AFAICT, our connector creates a key-value `qs` map where each value can be an object or array, and then leave it up to [request](https://www.npmjs.com/package/request) module to convert non-string values like objects into a query string.

Most Node.js servers use bracket style (this is BTW the style supported by OpenAPI spec too, see [`style:deepObject expand:true`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#style-examples)) and apparently `request` uses the same style too.

I think that encoding deep objects as JSON strings is a LoopBack-specific approach. Support for this format can be added to the connector behind a new feature flag. I think you will need to change the following place to detect object/array values and convert them to JSON string before the key/value pair is passed down to `request`/`qs`.

https://github.com/strongloop/loopback-connector-rest/blob/468052a79c7658034a1ad0df14c6525da95994ad/lib/rest-builder.js#L231-L237

A mock-up to illustrate what I mean:

```diff
 RequestBuilder.prototype.query = function(val, options) {
   var params = qs.parse(val);
   for (var key in params) {
-    this.template.template.query[key] = params[key];
+    if (options.encodeDeepObjectsAsJson && typeof params[key] === 'object') {
+      this.template.template.query[key] = JSON.stringify(params[key]);
+    } else {
+      this.template.template.query[key] = params[key];
+    }
   }
   return this;
 };
```

Would you like to contribute this feature yourself? We are happy to help you along the way. See our [contribution guide](https://loopback.io/doc/en/contrib/code-contrib.html#submitting-a-pull-request) to get started.
