### ISSUE TITLE
Rename `loopback/ioc`

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#178]
I'm proposing we name it:

to `loopback/context`

...but lets move forward - and not let the name slow us down.

**Comment by bajtos** [comment]
https://github.com/strongloop/loopback-next/pull/175#issuecomment-295326898

`@loopback/context` should be the name

It should export

```ts
export interface Container {
}

export class Context implements Container {
}
```

**Comment by bajtos** [comment]
In order to prevent merge conflicts and code churn, I'd like to get the foundation right before making changes in this module. Let's get the rename done right now - see #183.

The module is already exporting `class Context`, no change needed there.

IMO, adding `interface Container` is an incremental change that can be deferred until we have a need for such interface, let's leave it out of scope of this issue.

**Comment by bajtos** [comment]
Done via #183.
