### ISSUE TITLE
Generated openapi.json contains invalid URL for oasgraph

### ISSUE THREAD

**Issue by marioestradarosa** [strongloop/loopback-next#1780]
## Description / Steps to reproduce / Feature proposal

I am playing this weekend with oasgraph which needs the openapi.json file exposed from loopback 4, but the application supplies the openapi.json file with wrong url on servers property.  I have to manually add it in order to oasgraph resolves to the loopback server.

## Current Behavior
"servers": [
    {
      "url": "/"
    }
  ]

## Expected Behavior 
The generated openapi.json file should contain the `app.restServer.url` 

"servers": [
    {
      "url": "http://[::1]:3000"
    }
  ]

 
_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/lb4/Server.html#customize-how-openapi-spec-is-served.

Please note `/` is valid per OpenAPI spec. Since oasgraph expects an offline version of the spec and it does not have the base url to resolve `/`.

We can configure the cli to preset an option in the config per https://loopback.io/doc/en/lb4/Server.html#customize-how-openapi-spec-is-served.

**Comment by marioestradarosa** [comment]
Thank you @raymondfeng , I am almost completing my POC to use graphql as a library inside the loobpack4 app and serve the schema with this url.
