### ISSUE TITLE
.vscode settings require update for vscode > 1.27

### ISSUE THREAD

**Issue by DouglasWebster** [strongloop/loopback-next#1847]
## Description / Steps to reproduce / Feature proposal
With the release of vscode 1.28 the editor.tabcompletion setting has changed from the boolean true/false to a string "on", "off", "onlySnippets".

## Current Behavior
When a new project is generated and the vscode option chosen the .vscode workplace settings file is created.  This file has the `editor.tabCompletion` option set to `true`.

## Expected Behavior
With the release of vscode 1.28 the generated workplace settings file should have the 
 editor.`tabCompletion` should be set to `"on"`

**Comment by marioestradarosa** [comment]
@DouglasWebster  nice catch! Ref: https://code.visualstudio.com/docs/getstarted/settings .  Would you like to pull a PR for this? .  If so, please sign CLA at https://cla.strongloop.com/agreements/strongloop/loopback-next  and start contributing!

The file to update is located at `loopback-next/packages/cli/generators/project/templates/.vscode`

**Comment by bajtos** [comment]
@DouglasWebster thank you for reporting this issue! Your commit 
https://github.com/niyoko/loopback-next/commit/09f4d39320b35ce4ac51637b6264239c70bb40d6 looks pretty good, could you please open a pull request so that we can accept your changes? 

I think you forgot to change VSCode settings for loopback-next monorepo, see the file `.vscode/settings.json`:

https://github.com/strongloop/loopback-next/blob/a2ab86d3a3c721f28159585ca4e87bd8504476c4/.vscode/settings.json#L3
