### ISSUE TITLE
Automate per-commit publishing

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#194]
**ONLY for alpha releases, only changes last number (v4.0.0-alpha.*)**

When code lands on master, auto-publish all modules to NPM via a script.

Alpha + beta releases will be continuous deployment off master branch. Once we 4.0.0, we switch to push button deploy.

**Comment by superkhau** [comment]
Consider changelog implications at https://github.com/strongloop/loopback-next/issues/263

**Comment by bajtos** [comment]
I would personally prefer to switch to `0.x.y` versions for most (if not all) of our new packages. The only thing where `4.0.0-alpha.X` makes sense to me is `@loopback/core` as the top-level package people are going to install. But even there it feels to me more like a decision based on marketing rather than technical merit (since we are renaming `loopback` package to `@loopback/core`, I don't see why we could not reset the versioning and start from `0.x.y` too).

**Comment by superkhau** [comment]
+1 for actually sticking to semver in non @loopback/core packages. I agree with you the only argument for keeping @loopback/core at 4.0.0-alpha.X is purely marketing.

**Comment by superkhau** [comment]
Closing until we decide to take this further, ATM, normal publishing via a combination of `lerna publish` + `npm publish` seems adequate.
