### ISSUE TITLE
[Epic] Make sure documentation is up-to-date (2019Q2 Edition)

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1951]
## Description / Steps to reproduce / Feature proposal
Make sure:
- documentation is up-to-date
   - code exists in documentation is runnable
- apidoc is up-to-date and usable

**Comment by loredanacirstea** [comment]
At the end of this section: https://loopback.io/doc/en/lb4/HasMany-relation.html#configuring-a-hasmany-relation there are links for `create`, `find`, `delete`, `patch` - e.g. https://apidocs.strongloop.com/@loopback%2fdocs/repository.html#HasManyRepository.prototype.create.

None of them work anymore (they worked ~2 weeks ago). I did not find the `HasManyRepository` documentation at all in https://apidocs.strongloop.com/@loopback%2fdocs/repository.html
Has the location changed?

Maybe docs related - I have seen this entry in the changelog: `mark HasManyRepository as a readonly property` (https://github.com/strongloop/loopback-next/commit/39227eb) and the subsequent doc change. Is `HasManyRepository` now only `readonly`? Asking because I have some issues now with using `delete` on a `_createHasManyRepositoryFactoryFor` - possibly another issue, but I'm mentioning it in case the docs can be made more clearer.

**Comment by dhmlau** [comment]
@bajtos , it might be related to the clean up work you've done recently on `hasMany`?

**Comment by bajtos** [comment]
> it might be related to the clean up work you've done recently

Ah, looks like I forgot to list the newly added files in https://github.com/strongloop/loopback-next/blob/master/packages/repository/docs.json

@loredanacirstea would you like to contribute the fix yourself? Compare the list of TS files listed in `docs.json` with the actual files inside `packages/repository/src` and add those that are missing.

**Comment by dhmlau** [comment]
Closing as done.
