### ISSUE TITLE
Wrong error code when providing invalid parameter value

### ISSUE THREAD

**Issue by FabienCH** [strongloop/loopback-next#2102]
## Description / Steps to reproduce / Feature proposal
If you have an Entity with, for example, a string property and you try to post a number instead, the returned error code is "VALIDATION_FAILED", according to the documentation, it should be "INVALID_PARAMETER_VALUE"

## Current Behavior
Current response :
`"error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": ".description",
        "code": "type",
        "message": "should be string",
        "info": {
          "type": "string"
        }
      }
    ]
  }`

## Expected Behavior
Exepected response :
`"error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "INVALID_PARAMETER_VALUE",
    "details": [
      {
        "path": ".description",
        "code": "type",
        "message": "should be string",
        "info": {
          "type": "string"
        }
      }
    ]
  }`

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@FabienCH, IIUC, you have a model with a string property and when calling POST, you have a number in that property instead of a string.  In this case, it is behaving as expected to return "VALIDATION_FAILED" because the request body is invalid (one of the property values should be a string instead of a number)

Just in case you haven't seen it, here is the doc link on the error codes:
https://loopback.io/doc/en/lb4/Error-handling.html#known-error-codes

**Comment by FabienCH** [comment]
Hum I see, I just misunderstood the documentation. Thank you for your reply.

**Comment by dhmlau** [comment]
no problem. I'll close this ticket as resolved then. Thanks.
