### ISSUE TITLE
Documentation of loopback 4 Model is incorrect

### ISSUE THREAD

**Issue by opepermans** [strongloop/loopback-next#2133]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by emonddr** [comment]
We need to groom this to determine if we want an lb4 version of the https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html .

**Comment by dhmlau** [comment]
Instead of finding which content in https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html we can reuse in LB4, I think we can think the other way round to beef up the docs for [Model Decorator](https://loopback.io/doc/en/lb4/Model.html#model-decorator) and [Property Decorator](https://loopback.io/doc/en/lb4/Model.html#property-decorator), and see if there's anything applicable in the LB3 docs we can reuse so that we don't need to write it from scratch. 

- [Model decorator](https://loopback.io/doc/en/lb4/Model.html#model-decorator)
  - what's expected in `properties`?  Is it https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#properties? 
  - what's expected in `settings`?  Is it everything in https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#options? 
- [Property Decorator](https://loopback.io/doc/en/lb4/Model.html#property-decorator)
  - what are the valid values? would it be what's in the table for [general properties](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#general-property-properties)?

**Comment by b-admike** [comment]
Based on the discussion in this thread, I've compiled the following criteria for this issue.

# Acceptance Critera
- [ ] Figure out what can be passed into the model decorator (top-level) and how that affects the LoopBack 4 application. Because we are using legacy juggler bridge, we need to find out if the mapping of top-level keys works OOTB. For example, does passing in `@model({options:{...}})` work similar to how it does in LB3? The main keys to examine are `properties`, `settings`, `options`, `relations` because they're used often, but it'd be good to check all with a test app. Explain this in docs for [Model Decorator](https://loopback.io/doc/en/lb4/Model.html#model-decorator). Use https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html as the base to compare to and document differences.
- [ ] Figure out valid values for [Property Decorator](https://loopback.io/doc/en/lb4/Model.html#property-decorator) and explain them in more depth. Explore compliance with https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#general-property-properties and document discrepancies.
- [ ] For keys that do not work the same in LB4 as they do in LB3, create follow-up stories.
