### ISSUE TITLE
[Docs] How to share Models via components

### ISSUE THREAD

**Issue by pbalan** [strongloop/loopback-next#2193]
## Description / Question

I want to create components that consists of application logic that could be extended.

For example, I would like to create a module for users, access-token etc and reuse in every application. In LB3 we could create components with models. However, in LB4 I see that candidates to be shared as components are decorators, controllers, mixins, sequences etc.

**How can I share the models for reuse as components?**

Thanks.

**Comment by bajtos** [comment]
In LoopBack 4, models are consumed directly via TypeScript imports (or JavaScript/Node.js' `require`). Models describe data structures (schemas) only, they don't provide behavior like CRUD or key-value storage APIs - these behavior is provided by repositories.

In order to create a component with shared models, just export your models the usual TypeScript way.

I think this is something we should describe in our documentation better, I am labelling this issue as "Docs".
