### ISSUE TITLE
Does Loopback 4 have DB2 for iSeries support?

### ISSUE THREAD

**Issue by KerimG** [strongloop/loopback-next#2237]
I found out that Loopback 2 has a DB2 for iSeries connector over [here](https://loopback.io/doc/en/lb2/DB2-iSeries-connector.html). I thought, "Alright, I guess Loopback 4 has it too" but when I tried to create a data source via 

```
$ lb4 datasource
```

IBM DB2 for iSeries wasn't in the suggested list.

**Comment by dhmlau** [comment]
We have the same support for database connectors as LB2 & LB3, i.e. including DB2 iSeries. 
 It is interesting to note that even `lb datasource` doesn't have db2 iseries as one of the selection.  The json determining the list is here: https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json.

@strongloop/loopback-maintainers @smartmouse, do you know if there're particular reasons that this connector is not part of the available connectors list?  Maybe because it's not a commonly used connector?

**Comment by dhmlau** [comment]
Closing as resolved. @KerimG, if you have any follow up questions, please ping me and i can reopen this ticket.  Thanks.
