### ISSUE TITLE
The CLI cannot create anything except the application.

### ISSUE THREAD

**Issue by Groxot** [strongloop/loopback-next#2247]
## Description
Win 7 x64, node v8.9.4
When i write in project folder

>  lb4 datasource

```
D:\apps\mono-repo\server>lb4 datasource
? Project description: (datasource)
```
CLI try to create new project 

also service hase the same result
```
D:\apps\mono-repo\server>lb4 service
? Project description: (service)

```

**Comment by dhmlau** [comment]
@Groxot, `lb4 datasource` and `lb4 service` can only be run within a valid LoopBack 4 application.  In case you don't have it, you can run `lb4 app` to create an LB4 application first, and then create the datasource and services within the application folder.

It is strange though, because if the directory you're in is not a valid LoopBack 4 application, I got this error:
```
Generation is aborted: Error: No package.json found in <<my file path>>. The command must be run in a LoopBack project.
```

Hope it helps.

**Comment by dhmlau** [comment]
@Groxot, I thought the behavior on Windows might be a bit different, but I just tried it on Windows and it seems to be working as expected.
```
D:\loopback\test-0115>lb4 datasource
? Datasource name:
```

Having said that, there's a bug in cli and we just released a new release of `@loopback/cli`.  Could you please update and try again?  Thanks!

**Comment by Groxot** [comment]
> @Groxot, I thought the behavior on Windows might be a bit different, but I just tried it on Windows and it seems to be working as expected.
> 
> ```
> D:\loopback\test-0115>lb4 datasource
> ? Datasource name:
> ```
> Having said that, there's a bug in cli and we just released a new release of `@loopback/cli`. Could you please update and try again? Thanks!

@dhmlau Big thanks!!! Works great!
![image](https://user-images.githubusercontent.com/6220409/51227227-61d0ab00-1964-11e9-8f06-ebd4f4a0ce02.png)
