### ISSUE TITLE
Update Quicklab for Think Conference

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#2253]
## Description / Steps to reproduce / Feature proposal

Update our REST APIs with LB4 QuickLab to conform to latest changes made in the OASGraph module and `@loopback/cli`. Relevant content is found at https://github.ibm.com/IBMCode/Code-Tutorials/tree/master/create-rest-apis-minutes-with-loopback-4. Required access can be granted via https://w3.ibm.com/developer/join-ibmcode-ghe/.

**Comment by dhmlau** [comment]
## Acceptance Criteria
Make sure this quick lab instructions is up-to-date https://developer.ibm.com/tutorials/create-rest-apis-minutes-with-loopback-4/, including:
- [ ] update the instruction about oasgraph (we haven't updated it since the refactoring of oasgraph-cli
- [ ] run the tutorial once to make sure all the information is up-to-date.

**Comment by dhmlau** [comment]
@nabdelgadir , thanks for picking up the task.  Just wanna make sure... the Code@THINK is Feb 13.  You might need to ask for access, so please reserve some time for that too.  

I've looked at the [quick lab](https://developer.ibm.com/tutorials/create-rest-apis-minutes-with-loopback-4/) briefly again.  The only section needs to be updated is `Expose GraphQL APIs in LoopBack` and the up-to-date instruction can be found here: https://loopback.io/doc/en/lb4/exposing-graphql-apis.html.

The task is basically to update that section.  If we could get it done by Feb 11 EOD, that would be good.  Thanks.

**Comment by nabdelgadir** [comment]
Closed via https://github.ibm.com/IBMCode/Code-Tutorials/pull/511.
