### ISSUE TITLE
need @inject support in toDynamicValue

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#229]
Spike: https://github.com/strongloop/loopback-next/issues/246

**Comment by bajtos** [comment]
+1

Unfortunately, decorators like `@inject` can be applied only on class methods/ctors/arguments, not on standalone function. That's by design.

I am proposing a different API for injecting arguments to dynamic value factories:

```ts
// toFactory(inject: String[], fn: ()=>BoundValue)

app.bind('foo').toFactory(
 ['dependency1', 'dependency2'],
  (d1, d2) => 'the value');
);
```

Alternatively, we can create an overload of `toDynamicValue`. Unfortunately, TypeScript does not allow optional parameters before required ones, therefore the type signature would be rather ugly:

```ts
function toDynamicValue(arg1: String[] | ()=> BoundValue, arg2?: () => BoundValue) {
  // ...
}
```

**Comment by raymondfeng** [comment]
Here is my proposal:

```js
class MyFooFactory {
   constructor(
     private @inject('bar') bar: Bar
   ) {}

   create(@inject('baz') ...): Promise<Foo> {
   }
}

ctx.bind('foo').toFactory(MyFooFactory);
```

**Comment by ritch** [comment]
```ts
export class BindingProvider {
  @provide('authentication.user')
  getAuthenticatedUser(
    @inject('authentication.strategy') strategy,
    @inject('authentication.required') required
  ) {
    // ...
  }

  @provide('authentication.required')
  isAuthenticationRequired(
    @inject('controller.method.obj'
  ) method) {
    // ...
  }
}
```

The downside to providing a factory class per binding is the overhead for something that could otherwise be 3 lines of code...

**Comment by ritch** [comment]
```ts

// BindingProvider.ts (glue)
export class MyBindingProvier {
  foo(@inject('foo') foo) {
    return foo(foo);
  }
}

// still write simple functions...
export function foo() {
  // this is a pure function
}
```

**Comment by bajtos** [comment]
I am not a fan of requiring a Factory object either. I feel it goes against the spirit of JavaScript, where functions are first-class citizens.

Injecting dependencies at method level is tricky, I am still not convinced it's a good idea to start walking that path. Take `MyFooFactory` as an example: the factory instance is difficult to use outside of IoC container (`ctx`), because only part of `create` dependencies are injected at construction time.

```ts
class FactoryConsumer {
  constructor(private @inject('MyFooFactory') _fooFactory: MyFooFactory) {}

  doSomething() {
    const foo1 = _fooFactory.create(/* how to inject this? */);
    const foo2 = _fooFactory.create(/* how to inject this? */);
  }
}
```

Compare this with function-based approach:

```ts
class FactoryConsumer {
  constructor(private @inject('foo') createFoo: () => Foo) {}

  doSomething() {
    const foo1 = createFoo();
    const foo2 = createFoo();
  }
}
```

I am also concerned about performance costs - creating object instances adds pressure on Garbage Collector. I am not sure what's the life time of `MyFooFactory`, maybe this concern is not relevant here.

**Comment by raymondfeng** [comment]
Supported by https://github.com/strongloop/loopback-next/pull/343
