### ISSUE TITLE
Use decorators to register/bind Components and Extensions to the IOC container

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#244]
- [ ]  - use a `@Extension` decorator to register core extensions

```
   @Extension('Authentication')
   export class AuthenticationBinding {
       @bind('authentication.user')
        getAuthenticatedUser() {....}
   }
```

- [ ]  - use a `@component` decorator to register any class with a namespace
```
    @Component('namespace')
    export class AnyClass { ...}
```

- [ ]  - use a `@controller` decorator to  register a controller

```
   @Controller 
   @api(spec)
   export class UserController {...}
```

- [ ]  - use a `@Repository` decorator to register a datasource

```
   @Repository
   export class UserRepository {
      @inject('UserDB')
      let datasource: juggler.DataSource ; 
   }
```

**Comment by bajtos** [comment]
Let's defer this until we work on the declarative approach of building apps.

**Comment by dhmlau** [comment]
relate to: https://github.com/strongloop/loopback-next/issues/441

**Comment by bajtos** [comment]
I think this is no longer relevant. First of all, a decorator like `@Controller` cannot register the controller constructor with the application, because the app instance may not yet exist at the time the decorator was created. It would be useful if we have means to walk through all reflect-metadata entries and find those created by `@Controller`, in which case the app could find these controller classes. However, that still requires that some code is actually loading the source file of the controller. IMO, the code loading the controller source file (I assume it will be `@loopback/boot`) can process the exported classes and there is no need to use `@Controller` decorator.
