### ISSUE TITLE
Unable to install lb4 cli

### ISSUE THREAD

**Issue by pSnehanshu** [strongloop/loopback-next#2441]
## Description / Steps to reproduce / Feature proposal
System: Ubuntu 18.04.1 LTS
Node.js version: v11.10.0
NPM version: v6.8.0

## Current Behavior
When running `$ sudo npm i -g @loopback/cli`, the following error shows up:
<pre><span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Unexpected token &lt; in JSON at position 0 while parsing near &apos;&lt;HTML&gt;&lt;HEAD&gt;&lt;TITLE&gt;A...&apos;
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/snehanshu/.npm/_logs/2019-02-21T09_44_53_576Z-debug.log
</pre>
The log file is attached
[2019-02-21T09_44_53_576Z-debug.log](https://github.com/strongloop/loopback-next/files/2888656/2019-02-21T09_44_53_576Z-debug.log)

## Expected Behavior
Loopback 4 CLI should have been installed

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by jannyHou** [comment]
@pSnehanshu Can you try remove `sudo`? Ideally you don't have to install the cli with it.

**Comment by raymondfeng** [comment]
@pSnehanshu Can you install any other npm modules? Your log seems to hint there is an issue with http proxy.

**Comment by pSnehanshu** [comment]
@raymondfeng I was able to install `helmet` but not `express`.

**Comment by pSnehanshu** [comment]
@jannyHou I haven't tried that yet. I thought `sudo` is necessary to install global packages.

**Comment by pSnehanshu** [comment]
Guys, any help? I am still unable to install lb4 cli

**Comment by raymondfeng** [comment]
Are you able to access https://registry.npmjs.org/@loopback/cli?

If so, try the following:
1. Follow instructions at https://github.com/creationix/nvm to install `nvm`
2. After `nvm` is installed, run `nvm install 10` to install Node 10.x
3. Run `npm i -g @loopback/cli`.

**Comment by pSnehanshu** [comment]
Wow, mysteriously I'm now able to install lb4 cli. Thanks @raymondfeng (although I didn't follow your solution)

**Comment by paramanandbalara** [comment]
node -v
v16.14.1





 npm i -g loopback-cli
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated loopback-boot@2.28.0: This version is no longer supported, please upgrade to 3.x
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.14.1/lib/node_modules/loopback-cli/node_modules/ejs
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! sh: node: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-16T13_37_29_408Z-debug-0.log

**Comment by achrinza** [comment]
Hi @paramanandbalara, `loopback-cli` is for LoopBack 3, which has reached End of Life. For the LoopBack 4 CLI, use `@loopback/cli`.

**Comment by paramanandbalara** [comment]
npm install -g @loopback/cli
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated unicode-10.0.0@0.7.5: Use @unicode/unicode-10.0.0 instead.
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.14.1/lib/node_modules/@loopback/cli/node_modules/ejs
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! sh: node: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-16T14_33_39_047Z-debug-0.log
[root@centos-s-2vcpu-4gb-sgp1-test-01 /]# lb4

**Comment by paramanandbalara** [comment]
> Hi @paramanandbalara, `loopback-cli` is for LoopBack 3, which has reached End of Life. For the LoopBack 4 CLI, use `@loopback/cli`.

npm install -g @loopback/cli
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated unicode-10.0.0@0.7.5: Use @unicode/unicode-10.0.0 instead.
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.14.1/lib/node_modules/@loopback/cli/node_modules/ejs
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! sh: node: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-16T14_33_39_047Z-debug-0.log
[root@centos-s-2vcpu-4gb-sgp1-test-01 /]# lb4

**Comment by achrinza** [comment]
Based on the error provided, it looks like there's an issue with the PATH environment variable (i.e `node` command is not found). Unfortunately this is a hard issue for us to debug as the reason for the issue is quite circumstantial.

The general suggestion is to perform a full re-install of Node.js LTS and/or try `npx @loopback/cli`.
