### ISSUE TITLE
uri routes conflict

### ISSUE THREAD

**Issue by zhang-shengping** [strongloop/loopback-next#2447]
Use loopback4 define two similar uri like below:
  ```
  delete /test/v1/pools/{pool_id}/members/{member_id}
  delete /test/v1/pools/{id}
  ```
they are in different controller

```
export class MemberController {
    ...
    ...
    @del(prefix + '/pools/{pool_id}/members/{member_id}', {
      responses: {
        '204': {
          description: 'DELETE success',
        },
      },
    })
    async deleteMemberByID(
      @param.path.string('pool_id') pool_id: string,
      @param.path.string('member_id') member_id: string
    )
   ...
   ...
}
```

```
export class PoolController {
    ...
    ...
    @del(prefix + '/pools/{id}', {
      responses: {
        '204': {
          description: 'DELETE success',
        },
      },
    })
    async deleteById(@param.path.string('id') id: string): Promise<void>
    ...
    ...
}
```
If one of the above uri exists (enabled), the other uri cannot be visited, loopback4 always return 404 response for the other uri.

Is this a bug? or is there any way to fix it?

**Comment by dhmlau** [comment]
Transferring the issue to [`loopback-next` repo](https://github.com/strongloop/loopback-next).

**Comment by zongzw** [comment]
In fact, this issue does not relate to "different controller" you mentioned. 

Even if you put the two routes together into one controller, this issue can also be triggered if you declare/implement the longer path before the shorter path. That means:

```
# issue happens

delete /test/v1/pools/{pool_id}/members/{member_id}
delete /test/v1/pools/{id}
```
 
```
# NO issue happens

delete /test/v1/pools/{id}
delete /test/v1/pools/{pool_id}/members/{member_id}
```
 
**Why as it is?**

From `@loopback/rest/src/rest.server.ts` and `@loopback/rest/src/router/routing-table.ts`,  All route specs from all controllers would be registered one by one, in the alphebet order found. 

In your case, the route register sequence is: (M -> P)
1 MemberController: delete /test/v1/pools/{pool_id}/members/{member_id}
2 PoolController: delete /test/v1/pools/{id}

When `const route = this.findRoute(request);` during the API access, it trigger the `search` process in `@loopback/rest/src/router/trie.ts`, 

```
function search<T>(
  keys: string[],
  index: number,
  // tslint:disable-next-line:no-any
  params: {[name: string]: any},
  parent: Node<T>,
): ResolvedNode<T> | undefined {
  const key = keys[index];
  const resolved: ResolvedNode<T> = {node: parent, params};
  if (key === undefined) return resolved;

  const children = matchChildren(key, parent);
  if (children.length === 0) return undefined;
  // There might be multiple matches, such as `/users/{id}` and `/users/{userId}`
  for (const child of children) {
    const result = search(keys, index + 1, params, child.node);
    if (result) {
      Object.assign(params, child.params);
      return result;
    }
  }
  // no matches found
  return undefined;
}

```

` for (const child of children) {`: the children of `/pools/{id}` and `/pools/{pool_id}` becomes different; 
Iterating `/pools/{id}` before `/pools/{pool_id}/members/{member_id}` leads no problem, but the other case will fail.

When you put the 2 routes into one controller, the routes are registered in the order of their declaration. You didn't encounter the issue because you put `delete /test/v1/pools/{id}` before the other.

**Conclusion**: 

You can define our own Router to solve the problem as mentioned: https://loopback.io/doc/en/lb4/Routing-requests.html. 

But this should be an issue/bug of loopback4, personally speaking.

**Comment by zongzw** [comment]
In the error situation, the route from `const route = this.findRoute(request);` becomes`/*` instead of `/pools/{id}`

**Comment by achrinza** [comment]
@zhang-shengping Has the issue been resolved? If not, I think it would be best to keep this issue open should we revisit this issue.
