### ISSUE TITLE
Is there a built-in logging framework?

### ISSUE THREAD

**Issue by DatGuyJonathan** [strongloop/loopback-next#2511]
## Description / Steps to reproduce / Feature proposal

I see there's a way to create a log extension to log stuff in our code, but I'm wondering if there's a way to start LB4 with a log level to see debug messages that are happening in the internals of LB4.

I recall seeing in LB3 docs we could start the server with `DEBUG=* node .`, but that doesn't do anything anymore.

**Comment by raymondfeng** [comment]
We do use `debug` for LB4. You should be able to use `DEBUG=...` env var to dump out such messages.

**Comment by DatGuyJonathan** [comment]
I see, is `DEBUG=*` supported? I tried that and nothing new came out. If you have an example of a string I could hone in on , I'll give that a try.

**Comment by raymondfeng** [comment]
`DEBUG=loopback:*` does work for me.

**Comment by DatGuyJonathan** [comment]
Thanks @raymondfeng. I ran this on the terminal and saw the debug log lines. Turns out I was running this in debug mode (`DEBUG=* node --inspect-brk .`) in VS Code and didn't see the debug log lines. I also tried deploying the app to a cloud provider and didn't see the log lines either.

Do you have some insight on how the log lines are being outputted?

**Comment by dhmlau** [comment]
@DatGuyJonathan, just wanna make sure... before running `DEBUG=* node --inspect-brk .`, did you run `npm run build` to transpile the code?
Alternatively, you can do:
```
DEBUG=loopback:* npm start
```

It works for me as well. 
I'd like to close this issue since the command works for both @raymondfeng and I. @DatGuyJonathan , if you still encounter this issue, please feel free to reopen or open a new issue. Thanks.
