### ISSUE TITLE
[CLI] Adding nested configurations to model settings

### ISSUE THREAD

**Issue by yanamg7** [strongloop/loopback-next#2522]
## Description / Steps to reproduce / Feature proposal
We need to add some configuration to the model settings like

```ts
@model({ 
  settings: {
    mongodb: {
      collection: 'clients',
    },
  },
})
```

## Current Behavior
In configuration.JSON I put:

```ts
"modelSettings": {
			"mongodb": {
                                 "collection": "clients"
                          }
  },
```

The CLI generated model has a string instead of JSON:

```ts
@model({ settings: { "mongodb": { "collection": "clients" } } })
```

## Expected Behavior
The generated output should be 

```ts
@model({ settings: { 
                     mongodb: { 
                            collection: "clients"
            } 
    } })
```

I think in @loopback\cli\generators\model\templates\model.ts.ejs
instead of  `JSON.stringify(modelSettings)` should be `JSON.stringify(modelSettings).replace(/\"([^(\")"]+)\":/g,"$1:")`

**Comment by marioestradarosa** [comment]
Hi @yanamg7,  thank you 👍  for pointing it out and suggesting the solution. Would you like to contribute to the proposed solution?.  I believe that aside from changing the suggested line, we will need an acceptance test to make sure it solves the issue.

**Comment by yanamg7** [comment]
Hi Mario,
   Yes, I’ll contribute to the solution including test to check different model setting cases.

**Comment by dhmlau** [comment]
@yanamg7, thanks for your interest in contributing. We'll catch up on the issue #110. :)  This is mostly to add you to be in the  `@strongloop/loopback-next` github team, so that we can use this handle to ask for our users' feedback.  It's definitely not a blocker to contribute. :) 

We've just created a step-by-step guide in contributing to LB4.  Please take a look as well: https://loopback.io/doc/en/lb4/submitting_a_pr.html.  Looking forward to your PR!

**Comment by nabdelgadir** [comment]
Should be fixed via https://github.com/strongloop/loopback-next/pull/2843.
