### ISSUE TITLE
Support various notations for bindings 

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-next#258]
To bind a component to the container, there are two notations that we should support:

1. Bind to a path or hierarchical namespace, for example: 
    - `ctx.bind('/models/customer', Customer)`
    - `ctx.bind(models:customer', Customer)`

2. Bind to a complex object, for example:
    - `ctx.bind('req', req)`
    - `ctx.bind('req.myAttr', 'myAttr')`
    - `@inject('req.url`)
    - `@inject('req')`
    - `@inject('req.myAttr')`

**Comment by bajtos** [comment]
I would personally like to allow people to bind a full object like `request` and then inject a (deep) property of that object only:

```js
ctx.bind('http:request').to(request);
ctx.get('http:request.url'); // returns request.url
```

In that light, it makes sense to reserve `.` character as reserved and disallow people to create bindings with names containing a dot.

I think it's a bad idea to allow people to re-bind only a property of an complex object, e.g. via `ctx.bind('http:request.url')`, unless that's changing the real property on the owning object.

As for path/hierarchies/namespaces, I personally prefer `:` instead of `/` as a separator, but that's mostly subjective I guess.

**Comment by raymondfeng** [comment]
@bajtos I agree that we should prohibit `bind` with a key that contains `.`. It then boils down to the following conventions:
```js
ctx.bind('http:request').to(request) // Bind request object to 'http:request'
ctx.get('http:request') // Return request
ctx.get('http:request.url') // Return request.url
ctx.bind('http:request.url').to(request.url) // Not allowed
```
We also need to define container APIs so that we find/get a collection of bindings for a given namespace. This way, we can leverage it to support extension points, for example, get all registered `before save` hooks for a given model.

Between `:` and `/`, I don't have a strong opinion either. To me, `:` hints namespacing while `/` denotes a hierarchical path in a tree structure.

**Comment by superkhau** [comment]
* +1 for `:` and reserving `.`

>I would personally like to allow people to bind a full object like request and then inject a (deep) property of that object only...

+1, I think we should start simple and only go down that path if it becomes a commonly requested use case (IMO we could simply suggest rebinding the entire object again).

**Comment by bajtos** [comment]
I think we can close this issue now. #377 implemented support for injecting properties via `#` separator.
