### ISSUE TITLE
[Question] Can we make CI failed right away when commit linter fails? 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2742]
## Description / Steps to reproduce / Feature proposal
When the commit message of a PR does not adhere to the [commit message guideline](https://loopback.io/doc/en/contrib/code-contrib-lb4.html#commit-message-guidelines), Travis for other tests are still trying to run.  I've encountered a few times in some community PRs.  

Question: I'm wondering if there's any mechanism to make the Travis CI failed right away in this case instead of trying to finish running all the tests. 

Alternatively, when committing, I believe `husky` will tell us if the commit message does not adhere to our commit message guideline.  Perhaps we can make the error more prominent, if possible?

@strongloop/loopback-maintainers , thoughts?

**Comment by dhmlau** [comment]
@bajtos mentioned to look up: https://docs.travis-ci.com

**Comment by bajtos** [comment]
It's possible to divide Travis jobs into stages (see https://docs.travis-ci.com/user/build-stages/):

1. The first sequence runs commit linter only. If it fails then the build is aborted.
2. The first sequence runs all other jobs in parallel, no change from today.

The downside of such configuration is that successful builds will take longer to complete, because the commit linter is no longer executed in parallel with other jobs. Personally, I am reluctant to slow down successful builds.

Also conceptually, even if the commit message is malformed, I often want to see the actual `npm test` output, so that we can discuss the code changes regardless of metadata like commit messages. Commit message can be usually cleaned up by ourselves, so it's not a big deal if they are not correct on the first try (IMO).

If we eventually jump on Azure Pipelines (see https://github.com/strongloop/loopback-next/issues/3161), then it may be easier to show a failed check for commit linters, because AFAIK Azure Pipelines report one GH check for each job in the build matrix (as opposed to Travis).
