### ISSUE TITLE
[@loopback/CLI] Service generator not work

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#2778]
## Description

[Error] when creating a service and having datasources, it does not detect the datasource and it breaks

`Generation is aborted: Error: No datasources found at /Users/fran/Projects/xxxxxx-api/src/datasources. Please visit https://loopback.io/doc/en/lb4/DataSource-generator.html for information on how datasources are discovered`

![Captura de pantalla 2019-04-19 a las 14 58 30](https://user-images.githubusercontent.com/13822438/56425245-ac3f2c00-62b3-11e9-95d6-a8049146cb90.png)

**Comment by raymondfeng** [comment]
To create a service proxy, there must be a datasource backed by service-oriented connectors, such as
soap, rest, or gRPC. In LoopBack 4, we separate repositories (using databases) from service proxies. The error is thrown by design.

**Comment by privateOmega** [comment]
@raymondfeng Hey I was also under the assumption that there was something wrong with my cli for service generation and stumbled upon this comment by you.

May I ask what is the appropriate way to write a password hasher service? Because I am stumped by seeing [loopback example shopping project's password hashing service](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/services/hash.password.bcryptjs.ts). I know that that project satisfies the requirement specified by you by having a datasource backed by Service Oriented connector, but does it really need that? And also if that datasource was not there, where would be the ideal place to write a password hashing service?

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/3429. We're trying to generalize the `service` concept to allow both local services and proxies to remote services.
