### ISSUE TITLE
Need to hide loopback4 website header in auth explore

### ISSUE THREAD

**Issue by AnanthGopal** [strongloop/loopback-next#2781]
Need to hide loopback4 website header and footer in auth explore.

In my application, I used  JWT authentication, so that I add below code in my application, when I add below code, loopback4 website header, and footer are displayed in my explore. I don't need that fooder and header.

     this.component(AuthenticationComponent);
    this.bind(AuthenticationBindings.AUTH_ACTION).toProvider(AuthenticateActionProvider);
    this.bind(AuthenticationBindings.STRATEGY).toProvider(StrategyResolverProvider);
    this.bind(RestExplorerBindings.CONFIG).to({ path: '/explorer' });
    this.component(RestExplorerComponent);
    this.api({
      openapi: '3.0.0',
      info: {
        title: 'FARM API',
        version: '1.0.0',
      },
      paths: {}
    });
    // Bind JWT authentication strategy related elements
    this.bind(JWTAuthenticationBindings.STRATEGY).toClass(JWTStrategy);
    this.bind(JWTAuthenticationBindings.SECRET).to(JWT_SECRET);
    this.bind(JWTAuthenticationBindings.SERVICE).toClass(JWTAuthenticationService);
    // Bind bcrypt hash services
    this.bind(PasswordHasherBindings.ROUNDS).to(10);
    this.bind(PasswordHasherBindings.PASSWORD_HASHER).toClass(BcryptHasher);

![image](https://user-images.githubusercontent.com/13050426/56467110-0963ea80-6438-11e9-8603-bd82c2749edc.png)

**Comment by dhmlau** [comment]
@hacksparrow, IIRC, we allow customization in the API explorer for LB3.  Do we have that in LB4?  Thanks.

**Comment by hacksparrow** [comment]
You are seeing the LoopBack logo because you are using the REST Explorer hosted on http://explorer.loopback.io/. We can't remove our branding from our websites. 

However, you can host the REST Explorer component locally, which does not contain any branding material. Eg:

<img width="1136" alt="Screen Shot 2019-04-23 at 2 24 48 PM" src="https://user-images.githubusercontent.com/950112/56567946-98593a00-65d3-11e9-8b65-d13cd0d5c144.png">

**How to host the REST Explorer component locally**

1. `npm i @loopback/rest-explorer`
2. In `application.ts`:

import `@loopback/rest-explorer`:

```ts
import {
  RestExplorerBindings,
  RestExplorerComponent,
} from '@loopback/rest-explorer';
```

add the REST EXplorer component to the app in its constructor:

```ts
    this.bind(RestExplorerBindings.CONFIG).to({
      path: '/explorer',
    });
    this.component(RestExplorerComponent);
```

Or, you can install the latest version of the LB4 CLI, create a sample app and access the Explorer at http://localhost:3000/explorer/ and confirm there is no branding material.

```sh
npm install -g @loopback/cli
```

**Comment by dhmlau** [comment]
@hacksparrow , if we want to document this, should we add it in this page: https://loopback.io/doc/en/lb4/Serving-static-files.html, or maybe a new page under "how to"?

**Comment by hacksparrow** [comment]
@dhmlau this is an old behavior, the API Explorer is now hosted locally. We shouldn't need to document this. This page should be enough for the few, if any, old LB4 users who encounter this problem.
