### ISSUE TITLE
suggestion: rename rest sequences

### ISSUE THREAD

**Issue by jeremy-coleman** [strongloop/loopback-next#2783]
Sequence is a pretty common data interface and given that you're a data focused framework, having that on the rest resppnse api doesnt seem right (Just my opinion) Id go with series ,chain, batchHandler, step or something along those lines
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/-sequence/index.html

**Comment by hacksparrow** [comment]
Thoughtful suggestion.

@raymondfeng @bajtos "sequence" is something we might encounter in our messaging extension to LB4. Your thoughts?

**Comment by jeremy-coleman** [comment]
I have a follow on suggestion of using something like the common workflow language or the openstack equivalent , Cwl is reallynice though , you can see a reference impl herehttps://github.com/rabix/composer

**Comment by bajtos** [comment]
Thank you @jeremy-coleman for starting this discussion. I agree the term "sequence" is too generic and easy to confuse with other concepts not related to REST APIs.

Finding a good name is hard. As the joke goes, two most difficult problems in computer science are cache invalidation, naming and off-by-one errors :)

How about the name `RequestHandlingChain`, would it work better?

/cc @raymondfeng @strongloop/loopback-maintainers 

From the practical point of view, renaming `Sequence` to something else would be a very disruptive change. We will need to find a way how to make it incrementally so that we don't break all existing applications, or at least provide very easy upgrade path.

**Comment by raymondfeng** [comment]
In https://github.com/strongloop/loopback-next/pull/2927, I'm exploring a different way to implement a sequence - as a chain of intercepting actions. So it's possible to fulfill the duty with various techniques, such as:

- Composition with functions
- A chain of cascading interceptors

IMO, the responsibility of `Sequence` is to handle request/response at transport/protocol level to map endpoints to implementations. It plays similar roles as Express/Koa middleware.

**Comment by jeremy-coleman** [comment]
@raymondfeng  This is completely changing the original topic, but im a big fan of the tag filters, and tagging in general. It allows you to physically keep everything flat and create a tree or graph however you see fit ie: imagine a windows file system with all files in 1 folder and recreating the folder views based on tags each file instead of file paths.
