### ISSUE TITLE
[Q] What's the difference between datasource and connector?

### ISSUE THREAD

**Issue by mrdulin** [strongloop/loopback-next#2883]
I am reading the source code of
https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/repositories/repository.ts#L221

Why doesn't `loopback` use `connector` directly in `repository`?

**Comment by hacksparrow** [comment]
A **datasource** is a data access component composed of a **connector** and a **database**.

`this.connector = dataSource.connector as CrudConnector;` <-- TypeScript assertion to ensure the properties provided by `dataSource.connecto` match that's defined by `CrudConnector`, because `this.connector` is a `CrudConnector`.

**Comment by dhmlau** [comment]
Closing as answered.
