### ISSUE TITLE
lb4 relation should discard changes when something failed

### ISSUE THREAD

**Issue by ErwSim** [strongloop/loopback-next#3287]
## Suggestion

When something failed (ie: no pk or property already exists), changes that have been applied should be discarded

## Use Cases

It would permit to avoid reverting manually changes since the command has failed

## Examples

lb4 relation
  > fill
  > an error has occured
  > should be revert back

## Acceptance criteria

- [x] Do not generate any code if the the generation fails or gets aborted.
- [x] stretch goal: warn users earlier about missing Repository class (perhaps at the point right after asking for target and source model). 
- [ ] stretch goal: warn users when they are using customized FK name. 
     > - use customized foreign key name for belongsTo relation ( myCustomer in this case).
     > - use customized source property name for hasMany relation (e.g myOrder instead of orders).
because our the CLI doesn't support customizing names atm.
- [ ] Update documentation if there is behaviour change for prompts.

**Comment by dhmlau** [comment]
I've opened #4122 without knowing an existing issue. Cross posting here.

---

When running `lb4 relation` (for example following the [TodoList tutorial](https://loopback.io/doc/en/lb4/todo-list-tutorial.html)), it complained that there is no Repository class. However, in the `@hasMany` decorator has been added to todo-list.model.ts, possibly some other code had changed too.  


## Steps to reproduce
1. Run `lb4 example todo` to get the todo example 
2. Create the `TodoList` model according to https://loopback.io/doc/en/lb4/todo-list-tutorial-model.html#building-a-checklist-for-your-todo-models
3. Run `lb4 relation` command. It complained because I don't have `todo-list.repository.ts`. 
```
$ lb4 relation
? Please select the relation type hasMany
? Please select source model TodoList
? Please select target model Todo
? Foreign key name to define on the target model todoListId
? Source property name for the relation getter todos
? Allow TodoList queries to include data from related Todo instances? Yes
   create src/controllers/todo-list-todo.controller.ts
Generation is aborted: Error: File not found: /Users/dhmlau/loopback4-playground/loopback4-example-todo/src/repositories/todo-list.repository.ts
```
 
However, I noticed that in `todo-list.model.ts`, the `@hasMany` decorator has been added.
```
  @hasMany(() => Todo)
  todos: Todo[];
```




## Current Behavior



There were code changed even the command says it failed. 

## Expected Behavior


There should be no code change when the command failed to execute. 
Better yet, it warns the users that they need to have Repository class for both target and source model earlier. e.g. right after the prompts asking for the target and source model. 

## Link to reproduction sandbox



## Additional information



## Related Issues



_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

cc @agnes512

**Comment by agnes512** [comment]
Besides missing repos, as @ErwSim mentioned, when running `lb4 relations`, the decorators get generated even the generation is aborted with some errors. 

For example, `Order` and `Customer`, 
- Create a `belongsTo` relation with foreign key named `customerId` with `Order` and `Customer`.  
- Then create another `belongsTo` relation with foreign key named `myCustomer` with `Order` and `Customer` again.

`>>` It gets aborted with Err: `Error: property customer already exist in the repository`.


I think for these kind of cases, we should 
[1] Warn user when they 
  - use customized foreign key name for `belongsTo` relation ( `myCustomer` in this case).
  - use customized source property name for `hasMany` relation (e.g `myOrder` instead of `orders`).

 because our the CLI doesn't support customizing names atm. 

[2] Have reasonable error message for aborted generation.

[3] Do not generate any code if the the generation gets aborted if it's too hard to implement [2].

**Comment by dhmlau** [comment]
@agnes512, i've updated the acceptance criteria. Please edit accordingly. 
I didn't mention `Have reasonable error message for aborted generation` because if users hit ctrl+c, it is probably intentional or they are aware that they're aborting the generation?

**Comment by agnes512** [comment]
@dhmlau I meant the error messages we get when the generation goes wrong ( cause the one we have is not really accurate). Sorry for the confusion. 
And I just checked `ctrl+c`. It works fine. I think I messed it up with the issue I described above.
