### ISSUE TITLE
Best way to integrate CSRF protection?

### ISSUE THREAD

**Issue by shadyanwar** [strongloop/loopback-next#3589]
## Suggestion
Thoughts?

Also, information can be listed on:
https://github.com/strongloop/loopback-next/security/advisories

## Acceptance criteria

TBD - will be filled by the team.

**Comment by nflaig** [comment]
I implemented a solution that uses JWTs together with CSRF-Tokens but I guess that would be to specific already.

**Comment by shadyanwar** [comment]
@nflaig I think it's worthy of sharing! Please share it.

**Comment by nflaig** [comment]
Unfortunately, I am currently not able to open source the code but I can give a description on how it works and why I implemented it like this.

#### General concept
- stateless microservice architecture
- authentication service handles the login of users and returns the tokens
- JWTs are signed asymmetrically with the private key that only the authentication service holds
- other services can verify tokens without calling the authentication service just by using the public key
- tokens are access token, refresh token and CSRF token
- access token is used to authenticate the request (short lived token 5-15 minutes) it holds information about the user e.g. username, roles, ...
- refresh token is used to get a new access token from the authentication service (long lived token 24h to maybe even 1 year)
- the refresh tokens are needed in order to get new access tokens without requiring the user to provide credentials
- authentication service has a whitelist of all valid refresh tokens if a user logs out it gets removed from the list and no more access tokens can be requested with the refresh token

#### Why is the CSRF token required?
- access and refresh tokens are stored as HTTP cookies on the client with `httpOnly` and `secured` flag 
- this makes it vulnerable to CSRF (see [here](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html) for more information)

#### Why not just store the tokens in localStorage, no need for the CSRF tokens right?
yes then the CSRF token would not be needed but ...

**IMPORTANT:** DO NOT store any sensitive information in localStorage. And access tokens are basically the equivalent of the user credentials so they are VERY sensitive. localStorage makes them vulnerable to [XSS](https://www.owasp.org/index.php/Cross-site_Scripting_%28XSS%29) which means even if your code is secure any 3rd party library has to be secure as well because if not all the tokens belonging to your users can stolen and you probably wont even notice it.

I really feel the need to mention this because so many tutorials out there store tokens in localStorage which is one of the worst security practices that exists. Maybe the only ones that are worse is storing passwords in plain text and sending credentials over HTTP but thats it.

Localstorage was not introduced with HTML5 to store tokens so it shouldnt be used for it. If you still have doubts about that check the biggest 30-100 websites that are out there you will not find a single one that uses localStorage for tokens and of course they shouldnt. Another reference is the [OWASP recommendation](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#local-storage) on this topic which is very clear.

Sorry for the rant now back to the topic 😅

#### How is the CSRF token used?
- as mentioned before it is send to the client when logging in
- every request the client does needs the csrf token in specific header for example `csrf-token`
- the csrf token is a random string of characters encoded in base64url (make sure it is correctly generated)
- the csrf token is also stored in the signed access token and refresh token
- on the server the access/refresh token is validated and the csrf token in the token is compared with the csrf token in the custom header
- if the tokens do not match the request will be denied
- this resolves the csrf issue following the [Token Based Mitigation](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#token-based-mitigation)


 I hope the whole concept was somehow explained in an understandable way. If you have any questions feel free to ask. I am also open for suggestions and remarks.

**Comment by raymondfeng** [comment]
Can you try the following?
```ts
const csurf = require('csurf');
// See https://loopback.io/doc/en/lb4/Routes.html#mounting-an-express-router
app.mountExpressRouter('/', csurf());
```

**Comment by johnmbarry-nhvr** [comment]
The need for csrf tokens becomes irrelevant if JWTs are only stored in memory. We're implementing this approach with loopback4 and openapi-to-graphql. Reference:
https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#jwt_security

**Comment by nflaig** [comment]
@johnmbarry-nhvr interesting article and approach but I see two problems with it.

1. Storing JWTs in-memory on the client still leaves them vulnerable to XSS. If your javascript can use them so can the attacker.
2. In my opinion there is way to much the client needs to take care of. If you use a cookie only approach almost everything can be done by the auth server. However, I guess if you have a monolithic UI this might not be a problem.

What was also mentioned in the article and I think is a great and easy csrf protection is the SameSite cookie attribute. I am also currently, thinking about deprecating csrf tokens in my implementation since this is now mostly adopted by all browsers.

**Comment by achrinza** [comment]
Closing as solved.
