### ISSUE TITLE
Maintaining Loopback application up-to-date

### ISSUE THREAD

**Issue by gonzarascon** [strongloop/loopback-next#3608]
Hi! I was wondering if there is any way to maintain my Loopback App upgraded to the latests releases. 
Should I always upgrade `@loopback/cli`?  Is there any command inside the CLI which upgrades the app?

**Comment by hacksparrow** [comment]
We use [semantic versioning](https://docs.npmjs.com/about-semantic-versioning). Using `^` notation we can ensure that the latest non-breaking minor versions are installed every time you run `npm install`.

For example, if a dependency is declared like this:

```
 "@loopback/rest": "^1.16.3",
```

When version `1.16.4` or `1.17.0` of `@loopback/res` is released, they will be installed when you run `npm install`.

However, if `2.0.0` is released, it won't be installed, since a major release mean breaking changes.

**Comment by hacksparrow** [comment]
The CLI does two things:

1. Scaffold a new LoopBack app
2. Provide interfaces (commands) for creating / updating the artifacts of the app (like adding a model etc.)

When a new version of the CLI is released, it can affect one or both functionalities.

If the new version added new features or fixed some bugs related to scaffolding, it won't affect existing apps, it will affect only new apps you create with it.

If the new version added new features or fixed some bugs related to commands, it will affect your existing app too.

Minor releases are non-breaking, feature releases. It is highly recommended to update to them.

**Comment by hacksparrow** [comment]
That will have to be manual update.

**Comment by gonzarascon** [comment]
It would be nice to have these tips in the CLI documentation!
