### ISSUE TITLE
feat(booter-lb3app): signal to lb3app that it is mounted inside lb4

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#3624]
## Suggestion

I would like to send a signal to a lb3app that is is mounted inside of lb4.
With this knowledge the lb3app can conditionally disable some features, like error handling as described in https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application#tutorial

Is there already something like this?

## Use Cases

We are currently try to do a migration from lb3 to lb4, implementing this in incremental steps in one project. While doing this, we would like to start the backend as lb3 or lb4 including lb3app. Depending of the starting mode, some middleware in lb3 needs to configured / behave differently. All middleware is already registered programmatically in our lb3app.

## Examples

**Idea 1:**

https://github.com/strongloop/loopback-next/blob/ad4d22c684aca20df9b3e1282e831f6d9eefb1af/packages/booter-lb3app/src/lb3app.booter.ts#L75-L80
adding in line 77: `app.set('lb4', true);` (or maybe even the mounting mode)

Pro: works simply with express.set
Con: as lb3 is booting imedially, not sure if it is fast enough in all cases

**Idea 2:**

use an invironment variable:
https://github.com/strongloop/loopback-next/blob/ad4d22c684aca20df9b3e1282e831f6d9eefb1af/examples/lb3-application/src/application.ts#L25-L30

adding `process.env.LOOPBACK_VERSION = '4';` before line 28

Pro: simple
Con: feels dirty

## Acceptance criteria

TBD - will be filled by the team.

**Comment by bajtos** [comment]
@derdeka thank you for a clear description of your use case and the issue you have encountered 👍 

As you have mentioned in your analysis, calling `app.set` may not work reliably as it depends on internal timing of `loopback-boot`.

How about creating a new entry point in your LB3 application and then configuring LB4 booter to use that new entry point instead of the default `../lb3app/server/server`?

Personally, I think I would rework my LB3 project as follows:

- Change `server/server.js` into a factory function that accepts an `options` argument (e.g. whether to run in LB3-standalone or LB4-mounted mode)
- Add a new file, e.g. `server/standalone.js` that calls the factory function with no options. Modify "main" field in your `package.json` to point to this new file.
- Add a new file, e.g. `server/mounted.js` that calls the factory function with `options` set to trigger LB4-mounted mode. Modify your LB4 application to configure a different `path` for `lb3app` booter.

WDYT?

**Comment by derdeka** [comment]
Great idea, I did not think in that direction. I refactored my lb3 app in the suggested way. Works for me.
