### ISSUE TITLE
How to do customize query in loopback 4?

### ISSUE THREAD

**Issue by 1057437122** [strongloop/loopback-next#3798]
Hello , what i want to do is to query like this ' select a.id,b.name,c.size from a left join b on a.id=b.aid left join c on b.id=c.bid where a.id=xxxx';
if I use PHP laravel i can do with model like this 'A::query()->select('a.id','b.name','c.size')->leftJoin('b','a.id','=','b.aid')->leftJoin(c,'c.bid','=','b.id')->where('a.id','xxx')->get()
I didn't find any documents about this type query in loopback.

**Comment by 1057437122** [comment]
so ? This is not supported in lb4 ?

**Comment by dhmlau** [comment]
@1057437122, the GitHub issue was originally created in `loopback` repo where it should be in `loopback-next` repo since this is related to LB4.  That's why I transferred it to the right repo.

Regarding your question, there's some relevant code snippet mentioned in: https://github.com/strongloop/loopback-next/issues/3459#issuecomment-515443135.  Could you please give it a try? 
Here is the API docs link: 
- Datasource.execute: http://apidocs.loopback.io/loopback-datasource-juggler/#datasource-prototype-execute

**Comment by 1057437122** [comment]
> @1057437122, the GitHub issue was originally created in `loopback` repo where it should be in `loopback-next` repo since this is related to LB4. That's why I transferred it to the right repo.
> 
> Regarding your question, there's some relevant code snippet mentioned in: [#3459 (comment)](https://github.com/strongloop/loopback-next/issues/3459#issuecomment-515443135). Could you please give it a try?
> Here is the API docs link:
> 
> * Datasource.execute: http://apidocs.loopback.io/loopback-datasource-juggler/#datasource-prototype-execute

OK, thanks for the reply , I'll try

**Comment by dhmlau** [comment]
@1057437122, inspired by the example from https://github.com/strongloop/loopback-next/issues/3459#issuecomment-515443135. I've added one more endpoint / function in the controller so that it's easier to test.  

```
  @get('/test', {
    responses: {
      '200': {
        description: 'test for executing query',
      },
    },
  })
  async test(): Promise<any> {
    return this.customerRepository.dataSource.execute('SELECT * FROM CUSTOMER');
  }
```

Please note that the command you put as the parameter are specific to the database you're calling. I'm using Postgresql, but the above example is simple enough that is probably working for other relational database. 

Hope it helps!

With that, I'd like close this issue for this question.  If you encounter other issues, feel free to open a new issue. Thanks!
