### ISSUE TITLE
Testing LoopBack Apps with DI

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#380]
@raymondfeng @bajtos @superkhau 

Approach to writing tests using DI.

```ts
// comp.js
export const map = [
  'path/to/controllers/*',
  'mocks/controllers/*'
  // or 'bindingKey' eg. 'authentication.authenticate'
];

// tests.a.js
import {map} from 'comp.js'
import {given} from '@loopback/testlab'

given(map, ({InvitationController}, {UserController}) => {
  describe('InvitationController test', () => {
    it('should list invitations', async () => {
      const users = new UserController();
      const c = new InvitationController(users);
      const results = await c.listInvites();
      assertions(results);
    });
  });
});

// tests.b.js
import {map} from 'comp.js'
import {given} from '@loopback/testlab'

given(map, ({FooController}) => {
  describe('FooController test', () => {
    it('should not error', () => {
      const f = new FooController();
    });
  });
});

// psuedo impl
function given(map, ctx?, fn) {
  if(!ctx) ctx = createContext();
  const args = [];
  for (path of map) {
    if (isPath(path)) {
      const modules = requireWithGlob(path) // => {UserController: userControllerModule}
      for(let [name, module] of Object.entries(modules)) {
        app.bind(name).to(module)
      }
      args.push(modules)
    } else {
      // its a binding key
      args.push(ctx.getSync(path))
    }
  }
  fn.call(args)
}
```

**Comment by ritch** [comment]
Another example using stubs:

```ts

// my-sequence.js
class MySequence {
  constructor(@inject('auditService') audit) {}
  run(req, res) {
    this.audit(req, res)
    return this.super.run(req, res)
  }
}

// audit-stub.js
export const audit = sinon.stub().returns(true);

// test.c.js
const app = new Application()
const map = [
  {sequence: 'my-sequence.js'},
  {'auditService': 'audit-stub.js'}
]
given(map, app, (sequence, auditStub) => {
  it('calls the audit service', () => {
    client = new Client(app)
    await client.get('/')
    auditStub.wasCalled()
    // how to assert audit service was called
  })  
})
```

**Comment by bajtos** [comment]
-1 for defining mocks outside of the test code that uses them. The way how I understand IoC/DI, the goal is to allow each unit test to create its own unique specialized & focused mocks to satisfy the dependencies they want to alter. Also since we are talking about unit-tests, they should be constructing class instances directly, providing any dependencies explicitly from the code.

```ts
// production code
class InvitationController {
  constructor(
    @inject('repositories.InvitationRepository') private readonly _repo: Repository<Invite>) {}

  public listInvites(): Promise<Invite[]> {
    return this._repo.list();
  }
}

// unit-test

it('returns list of invites', () => {
  const repo: Repository<Invite> = sinon.mock(...);
  // setup the mock - find() should return the value we want
  const controller = new InvitationController(repo);

  const result = await controller.listInvites();

  expect(result).to.eql(...);
});
```

When it comes to integration-level testing, I suppose we may want to use rebind certain values in the app context to customize the behaviour. However, I am not sure if that's actually a good solution, because once we start using mocks, then we are not testing how different units are integrated together and most importantly.

The second example that's testing auditing, I think there should be two different tests:

 - A unit test of `MySequence` where we supply a mocked Audit and verify that the sequence reports audit logs.
 - An integration or acceptance test verifying that the application is wired in such way that audit logs are stored in the expected location (a log file, a database table, a backed service).

Neither case requires the tests to be aware of our DI.

An example of MySequence unit test:

```ts
// my-sequence test
it('reports audit logs', () => {
  const audit = sinon.stub().returns(true);
  const sequence = new MySequence(audit);
  
  await shot.inject((req, res) => sequence.run(req, res), { uri: '/' });
 
  auditStub.wasCalled()
});
```

**Comment by superkhau** [comment]
I can swing either way. I find the DI container for testing in general is for getting at mocks. That said, you can always do the same without the DI container. Other ways to get at shared mocks (ie. global singleton, etc). The nice thing about he top impl is you decouple the "newing" (which is what you do in your examples @bajtos) and use factories from the container instead. That said, I think it depends on the audience/size of project to determine whether you need DI in tests.

**Comment by dhmlau** [comment]
Related to https://github.com/strongloop/loopback-next/issues/393

**Comment by bajtos** [comment]
The testing strategy with concrete examples has been already described here: http://loopback.io/doc/en/lb4/Implementing-features.html
