### ISSUE TITLE
Data model validation required.

### ISSUE THREAD

**Issue by UNSWZen** [strongloop/loopback-next#3913]
## Suggestion
At the moment I can only find Open API schema validation but not the business logic validation. I'd like to see some custom validation rules as in lb3, and possibly if the validations can be done outside of the controller(eg: sequence maybe?)

1. Custom validation rules.
2. The `additionalProperties` defined in `@model` decorator will be ignored by `buildModelDefinition`,
and `jsonToSchemaObject` at line 77:
```
      case 'additionalProperties': {
        if (typeof json.additionalProperties !== 'boolean') {
          result.additionalProperties = jsonToSchemaObject(
            json.additionalProperties!,
          );
        }
        break;
      }
```
If the type of additionalProperties is boolean it will just be filtered out, is there any reasons of doing that?

3. I also tried do the validation myself in the sequence level, but the parsed body defined by `@requestBody` is of type 'object'. It would be nice if it can be the class specified in the function signature so that I can utilise some of the methods(say isValid()) defined in the class.

## Acceptance criteria
TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@UNSWZen, sorry about the very late reply! Business logic validation can be added through interceptor. Please see the validation example app: https://github.com/strongloop/loopback-next/tree/master/examples/validation-app.

It's been 5 months since the issue has opened, so I'd like to close this issue as done. Please feel free to open a new issue if you run into other problems. Thanks!
