### ISSUE TITLE
todolist example not work correctly(inclusion show in document but not same with the response)

### ISSUE THREAD

**Issue by st119848** [strongloop/loopback-next#3960]
## Steps to reproduce

Run the lb4 example command to select and clone the todo repository:

lb4 example todo-list
Switch to the directory.

cd loopback4-example-todo-list
Finally, start the application!

$ npm start

Server is running at http://127.0.0.1:3000

or i clone your entire github and start in example todolist folder the result is the same .

## Current Behavior

In the api document show example result with inclusion(relate model) but actual result format not same as example result.

## Expected Behavior
Response same pattern as example result (with inclusion (relate model))

**Comment by st119848** [comment]
Ok this is what i expect. and the document api show

**Comment by nabdelgadir** [comment]
Hi @st119848, so this is actually a limitation of the explorer (https://github.com/strongloop/loopback-next/issues/2208). If you notice the request url, it's http://localhost:3000/todo-lists instead of http://localhost:3000/todo-lists?filter[include][][relation]=todos. Try using the url instead of doing the request through the explorer.

**Comment by st119848** [comment]
thank you i will try to use api with url and filter url.

**Comment by st119848** [comment]
what if i want to use more inclusion in the inclusion what pattern url will be ? or you can send me about link to read about it

**Comment by st119848** [comment]
relate to this issue https://github.com/strongloop/loopback-next/issues/3453
