### ISSUE TITLE
 How to run LB3 app tests when the app is mounted in a LB4 project

### ISSUE THREAD

**Issue by kevintc** [strongloop/loopback-next#3978]
## Steps to reproduce
Migration from lb3 to lb4, our legacy app lives in `./lb3app` and tests (using *Mocha*) are in `./lb3app/tests`

## Current Behavior
In `./lb3app/tests/main.js`, we have `const app = require('../server/server')`.
When trying to run the tests using `mocha ./lb3app/tests/main.js` `app` is undefined.

I tried `typescript-require` and:
```javascript
const { ApiApplication } = require('../../src/index.ts')
const app = new ApiApplication()
```

## Expected Behavior
I expected a way to call the new lb4 `app` object from `lb3` tests framework.
Or do we need to write all the tests again in `.ts`?

## Link to reproduction sandbox
Our current setup is close to this one: https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application
I'll see if I can add `mocha` to it.

## Additional information
>`node -e 'console.log(process.platform, process.arch, process.versions.node)'`:

`darwin x64 10.16.0`

>`npm ls --prod --depth 0 | grep loopback`:
```
├── @loopback/boot@1.5.8
├── @loopback/booter-lb3app@1.3.2
├── @loopback/context@1.23.2
├── @loopback/core@1.10.4
├── @loopback/openapi-v3@1.9.9
├── @loopback/repository@1.15.1
├── @loopback/rest@1.20.1
├── @loopback/rest-explorer@1.4.1
├── @loopback/service-proxy@1.3.8
├── loopback@3.26.0
├── loopback-boot@3.3.1
├── loopback-component-explorer@6.4.0
├── loopback-component-oauth2@3.2.0
├── loopback-component-passport@3.10.0
├── loopback-connector-es@1.4.1
├── loopback-connector-mongodb@3.9.2
├── loopback-connector-mysql@2.4.1
├── loopback-connector-rest@3.5.0
├── loopback-context@3.4.0
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@nabdelgadir, could you please take a look? Thanks!

**Comment by nabdelgadir** [comment]
Hi @kevintc, can you try:

```ts
const {ApiApplication} = require('../../')
const app = new ApiApplication()
```

**Comment by bajtos** [comment]
@kevintc thank you for starting this discussion.

First of all, why would you like to access LB4 application from your LB3 tests? In my mind, this creates a cyclic dependency (LB4 app depends on LB3 app, but your LB3 tests want to depend on LB4 app).

Having said that, I think we didn't consider how to run LB3 app tests when the app is mounted in a LB4 project, so I am not surprised there are rough edges now.

**Comment by romain-ortega** [comment]
Hey, thanks for your answers @bajtos @nabdelgadir !

We managed to make tests work by booting both LB4 app (@nabdelgadir method 👍) and LB3 app (via require `../server/server`)

With LB4 Application we can retrieve open API spec and execute our end-to-end tests.

However, we were wondering if there is a way to access our LB3 methods directly from LB4 application, without requiring LB3 server manually ?

**Comment by nabdelgadir** [comment]
> However, we were wondering if there is a way to access our LB3 methods directly from LB4 application, without requiring LB3 server manually ?

Sorry for the super delayed response! Do you have an example of a LB3 method that you'd want to access directly?

**Comment by dhmlau** [comment]
@bajtos, could you please add acceptance criteria? thanks!

**Comment by bajtos** [comment]
>  could you please add acceptance criteria?

Hmm, I think we need to clarify what user stories we want to document. Here is what I am thinking about:

As a user migrating from LB3 to LB4, I created a new LB4 project and mounted my LB3 application as explained in https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application

Now I want to run my existing LB3 tests as part of LB4 project's `npm test` command. How can I accomplish that? We should have a documentation for this step, I think [README](https://github.com/strongloop/loopback-next/tree/master/examples/lb3-application/README.md) of lb3-application is a good place for such docs.

There are two kinds of tests we need to support. Ideally, there should be a way how to run these tests from the original JavaScript files stored in the LB3 project, so that users don't have to migrate all test files to LB4.

1. Acceptance-level tests making HTTP calls to invoke application logic, e.g. `POST /users/login`. I think this is easier because the tests need just the port number where the top-level app is listening on, this app can be the LB4 (or Express) app.

2. Integration-level tests that are using JS API to call application logic, e.g. `MyModel.create()`. These tests need a way how to access  LB3 artifacts of the LB3 application booted by LB4. I think may be the issue @kevintc has run into.

As a bonus, let's take a look at accessing LB3 models from LB4 app (e.g. from LB4 controllers). In LB3, models are access via `app.models.MyModel` or `MyModel.app.models.AnotherModel`. Now the question is how to access the LB3 `app` object that was booted by LB4? Maybe we need to enhance the booter to bind the LB3 `app` object to LB4 application context, so that we can use regular dependency injection to access that app object from other LB4 code? Alternatively, it may be better to bind all LB3 models instead of the LB3 app object, so that we can inject only specific LB3 models to LB4 code, in the same way we are injecting only specific LB4 repositories to LB4 controllers.

Acceptance criteria for the spike: investigate the following four tasks and propose a solution for each one. Create follow-up stories to document them and make any necessary runtime improvements.

1. How to include tests from LB3 app in LB4 test suite. This may be as easy as adding `lb3app/tests/**/*.js` to `mocha` arguments. LB3 tests are not expected to pass yet, see the steps below.
2. How to change acceptance-level tests to use the outer LB4 app as the server to talk to, not the LB3 app. With the proposed changes in place, the acceptance-level tests should pass now.
3. How to change integration-level tests to accommodate for the new LB4+LB3 and pass.
4. How to access LB3 models (and datasources?) from LB4 code using dependency injection.

**Comment by agnes512** [comment]
Thank you so much @bajtos ! The spike is created in https://github.com/strongloop/loopback-next/issues/5004.

**Comment by dhmlau** [comment]
Spike #5004 is done. The follow up tasks are planned for May milestone: #5301.

**Comment by dhmlau** [comment]
Turning this issue as an epic.

**Comment by dhmlau** [comment]
All the tasks in this epic are done. Closing this as done!
