### ISSUE TITLE
Handler/Sequence-function sugar API

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#399]
Implement support for the APIs described in the following two wiki pages:
 - https://github.com/strongloop/loopback-next/wiki/Hello-world
 - https://github.com/strongloop/loopback-next/wiki/Sequence

Basically, we need to implement the following API:

```ts
app.handler((sequence, request, response) => {
  const spec = {params: {name: 'string', source: 'query'}};
  const params = sequence.parseParams(request, spec);
  sequence.send(response, `hello ${params.name}`);
});
```

**Comment by superkhau** [comment]
Interesting note from short discussion with @bajtos today. Why don't we only use classes instead of directly passing a function? The initial idea was the simplest possible implementation, but passing in a Fn is such an edge case. As suggested by @bajtos, classes are supported all the way back to Node 4? I guess one good argument is that you don't need a class at all for demonstration purposes/flexibility -- maybe we should keep things simple and enforce our opinion here. Thoughts? @ritch @raymondfeng

**Comment by bajtos** [comment]
On the second though, I guess the function-based handler api makes sense for people who would like to use LoopBack but don't want to get into OOP/DI.
