### ISSUE TITLE
LoopBack emits invalid OpenAPI spec document - `examples` field is not allowed in OpenAPI

### ISSUE THREAD

**Issue by stoffason** [strongloop/loopback-next#4043]
## Steps to reproduce

After updating `@loopback/openapi-v3` to `1.10.0`, the schema produced does not create valid code with openapi-generator  --typescript-angular

## Current Behavior

The lb4 schema now adds an additional property "additionalProperties: true", which gives invalid generated code with openapi-generator

Additional new properties generated "examples : [Array]"  and "examples: 'string' " also now cause errors when running openapi-generator

## Expected Behavior

openapi-generator  works fine with all previous versions 1.9.10, no errors and all valid code.

## Additional information

openapi-generator v4.2.1 SNAPSHOT

after updating lb4 to latest build, then running code generator as usual, I get errors when building a from loopback schema

...'(get).parameters.[xxx].schemas.examples is unexpected

Seems the new properties 'examples: [Array]' is not valid... 
after removing examples from scheme, code is generated without error, but also now produces invalid code.

Looks like the other new property, "additionalProperties: true" added to the lb4 schema causes the openapi-generator generated code to be invalid.

Example controllerService generated would look like...
 
```javascript
public xxxControllerCount(where?: object, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
```

it now generates the following which is not valid

```javascript
public companyPolicyControllerCount(where?: { [key: string]: object; }, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
```
Removing "additionalProperties: true" or manually changing the generated api schema setting to false, gives correct code.

Can be reproduced with standard lb4 cli generated app, and latest openapi-generator

Thanks

**Comment by bajtos** [comment]
Thank you @stoffason for reporting the issue. I understand how annoying it is that a change in LB4 broke generation of your client-side code.

> Looks like the other new property, "additionalProperties: true" added to the lb4 schema causes the openapi-generator generated code to be invalid.

Quoting from https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#properties:

- _additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema_

In LB4, we are setting `additionalProperties: true` to indicate that extra properties are allowed. From my point of view, LB4 is emitting a valid OpenAPI spec document. 

IIUC, the code generator is also doing the right thing by allowing a free-form TypeScript object via `{ [key: string]: object; }`.

If you feel that openapi-generator should be emitting a different TypeScript type for such parameters, then please open an issue in openapi-generator. Feel free to mention my handle in that issue so that I can join the discussion and perhaps help you explain the problem if needed.

> ...'(get).parameters.[xxx].schemas.examples is unexpected
>
> Seems the new properties 'examples: [Array]' is not valid...
> after removing examples from scheme, code is generated without error, but also now produces invalid code.

Interesting! This may be a legitimate problem in our implementation.

Here is what OpenAPI specifications says in [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#schema-object) section:

- It list properties properties that are taken directly from the JSON Schema definition and follow the same specifications, `examples` is not listed.
- Then there are properties taken from the JSON Schema definition where the definitions were adjusted to the OpenAPI Specification, `examples` is not listed either.
- Then there is this important sentence (emphasis is mine): 
  **Additional properties defined by the JSON Schema specification that are not mentioned here are strictly unsupported.**
- Finally, there is a list of [Fixed fields](https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#fixed-fields-20), which describes `example` field as follows:

  - Field Name: `example`
  - Type: `Any`
  - Description: A free-form property to include an example of an instance for this schema. To represent examples that cannot be naturally represented in JSON or YAML, a string value can be used to contain the example with escaping where necessary.

My take: the solution presented by https://github.com/strongloop/loopback-next/pull/3911 is incorrectly copying `examples` field from JSON Schema to OpenAPI Schema Object. We should fix it by removing the following line:

https://github.com/strongloop/loopback-next/blob/eb1a0ae7a433e566f413a7e3c518b3aeff5374c4/packages/openapi-v3/src/json-to-schema.ts#L123

@stoffason would you like to contribute this fix yourself? 

See our [Contributing guide](https://loopback.io/doc/en/lb4/code-contrib-lb4.html) and [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html) to get started.

@derdeka you are the original author of this problematic line, do you remember if you had any particular arguments or needs for copying the entire `examples` array from JSON to OpenAPI schema?

**Comment by derdeka** [comment]
@bajtos The intension of copying `examples` was to keep the original behavior - before PR #3911 `examples` was copied by this lines:
https://github.com/strongloop/loopback-next/blob/9bd5cf0035d36cab5fb2962dd4e53cb3ac0bdf6a/packages/openapi-v3/src/json-to-schema.ts#L128-L130
