### ISSUE TITLE
Loopback-Next Facebook Community To Help Each Other

### ISSUE THREAD

**Issue by vikramkh** [strongloop/loopback-next#4075]
Hey guys. I opened up a facebook group for loopback-next users to get help from each other; providing less saturation on SO and this issue group.  Feel free to join/ask questions/help each other out. If this is not ok please let me know! Join here:

https://www.facebook.com/groups/1679283695536187/?hc_ref=ARSAJK8uq0eUPIJOq871iRgs5MpsSEzhrC4YdWFWBu573DvSmpQaZii0aHJJDPTJaVk

**Comment by dhmlau** [comment]
Thanks @vikramkh!  We have created a Slack workspace earlier hoping to achieve a similar purpose.  However, it has only been lightly use and we were [discussing](https://github.com/strongloop/loopback-next/pull/4030#issuecomment-549057758) whether it's a good time to open it up for people to join. The downside for our Slack workspace is that since it's free, it only keeps the most recent 10,000 messages.

I'd like to hear from @strongloop/loopback-maintainers , especially @bajtos and @raymondfeng who had been given more thoughts on this.

**Comment by vikramkh** [comment]
No problem! I didn't know about the slack channel and no one has yet joined the facebook group :(. I'd gladly hand over the group moderation to an admin here, and maybe some promotion will encourage people to join, as I have personally found facebook groups to be very helpful in answering questions!

**Comment by marioestradarosa** [comment]
Indeed, FB groups are good, but it should be administered by Loopback. Perhaps moderators from the community, similar to Node JS Official FB groups.

**Comment by bajtos** [comment]
Personally, I am strongly against Facebook because of moral reasons. Having said that, I am not going to enforce my opinions on others. If somebody likes to discuss LoopBack on Facebook, then I am fine with that, as long as I can stay away.

We already have a chat room on Gitter, see https://gitter.im/strongloop/loopback

Maybe we should publicize the Gitter room more? For example in our issue templates, see the discussion in https://github.com/strongloop/loopback-next/pull/4030

**Comment by marioestradarosa** [comment]
>> Maybe we should publicize the Gitter room more? 

👍

**Comment by dhmlau** [comment]
I think we had some discussion in the past about Gitter room vs Slack.

Gitter room is better because:
- there are already 3000+ people in Gitter. It might be hard to build up that mass in Slack in a shorter term
- users are already helping each other out in there without the maintainers really monitoring. 

Slack is better because: 
- the LB core maintainers are using Slack on a daily basis. It has less friction to use if we adopt Slack.
- we can continue the conversation in threads, it's easier to read the messages.
_Free plan for Slack only keeps the more recent 10,000 messages. It may not be a big issue but important to bring it up._

I'm fine either way (also less favorable on Facebook too).

**Comment by vikramkh** [comment]
I like gitter/slack but the problem I usually have with chat channels is the confusion if multiple people ask questions. I thought facebook posts would allow for more segregated issues, and would show up while you're 'taking a break' or browsing social media rather than watching a specific channel, thereby allowing for more views per issue. I understand other concerns though.

**Comment by dhmlau** [comment]
@vikramkh, I think at this point, we prefer not to divert our effort in maintaining one more Facebook group. Feel free to keep your Facebook group though, and please also keep in mind we have other social media channels: 
- [Twitter](https://github.com/strongloop): it has the most updated info. Please follow us there! 
- [Facebook page](https://www.facebook.com/strongloop) : this one is more for announcements
- [StrongLoop community group on LinkedIn](https://www.linkedin.com/groups/5046525/): same as Facebook, it's more for announcements.

With this reason, I'd like to close this issue. Thanks again for your interest in LoopBack!
