### ISSUE TITLE
lb4 repository,model,controller commands generate artifacts with 'lint' issues

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#4205]
I tried running : npm run test 

after creating the artifacts from the Todo tutorial, and the linting after the tests fail.

I did a comparison of the generated files, and the files after `npm run lint:fix` and these are the differences I found:

Controller:

![image](https://user-images.githubusercontent.com/6864736/69568094-efb7f200-0f88-11ea-988e-c56c0d3cdddc.png)

Repository:

![image](https://user-images.githubusercontent.com/6864736/69568131-09593980-0f89-11ea-9be8-a2bbd35804c8.png)

Model:

![image](https://user-images.githubusercontent.com/6864736/69568200-27bf3500-0f89-11ea-8ac4-55ac273b7934.png)

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

## Acceptance Criteria

- [ ] Create the Todo application with the lb4 commands, and then ensure the `npm run lint` completes without error.
- [ ] fix templates ( might need to update snapshots test as well)
- [ ] add solutions to fix the lint error in docs

**Comment by raymondfeng** [comment]
Use `--format` flag. See `standard options` at https://loopback.io/doc/en/lb4/Application-generator.html#options.

**Comment by bajtos** [comment]
> Use `--format` flag. See `standard options` at https://loopback.io/doc/en/lb4/Application-generator.html#options.

Personally, I consider that approach as a workaround. We should strive to emit code that passes our linter rules.

I think the issue pointed out by @emonddr should be easy to fix.

If we think `--format` is the solution that more people should use, then let's find a way how to enable that option by default.

**Comment by dhmlau** [comment]
@emonddr, could you please add the acceptance criteria? Thanks.

**Comment by jannyHou** [comment]
I am on the latest cli `@loopback/cli@1.27.0`, the created todo example (`lb4 example` --> select todo) already fixes the lint errors in CONTROLLER and MODEL:

- model:
![Screen Shot 2019-12-30 at 2 14 39 PM](https://user-images.githubusercontent.com/12554153/71596859-f8af5c80-2b0e-11ea-9019-2272056039e2.png)
- controller:
![Screen Shot 2019-12-30 at 2 17 25 PM](https://user-images.githubusercontent.com/12554153/71596893-21cfed00-2b0f-11ea-9685-9ae01294fbf6.png)

The REPOSITORY has the correct code: changing
```ts
constructor(@inject('datasources.db') dataSource: juggler.DataSource) {
    super(Todo, dataSource);
  }
```
to 
```ts
constructor(
  @inject('datasources.db') dataSource: juggler.DataSource
) {
    super(Todo, dataSource);
  }
```
results in lint error, so we should stay with the current behaviour.

There is a new lint error found in the controller file, it's already fixed in the latest master branch, so a new release will get rid of it:

![Screen Shot 2019-12-30 at 2 13 32 PM](https://user-images.githubusercontent.com/12554153/71596860-f8af5c80-2b0e-11ea-9a8b-468d7eb77383.png)

**Comment by jannyHou** [comment]
I will wait for a new release before closing this story.
