### ISSUE TITLE
feat(rest): refactoring common filter schemas

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4328]
Related: https://github.com/strongloop/loopback-next/issues/4290#issuecomment-565000888

Currently, the filter schemas are generated inline in the OAS `openapi.json` document. This may lead to the filter schemas being repeated within the same OAS docs.

## Suggestion

Instead, these schemas should be refactored into `/components/schemas`.

## Use Cases

The OAS document may be more compact and have increased readability as the filter schemas will not be repeated. Furthermore, the generated client-side code may also benefit similarly.

## Examples

(Taken from: https://github.com/strongloop/loopback-next/issues/4290#issuecomment-566683037)
```
{
  "TodoFields": {
    "title": "TodoFields",
    "type": "object",
    "properties": {
      "id": {
        "type": "boolean"
      }
     // ...
    }
  },
  "TodoFilter": {
    "title": "TodoFilter",
    "type": "object",
    "properties": {
      "where": {
        "type": "object"
      },
      "fields": {
        "$ref": "#/components/schemas/TodoFields"
      },
      "offset": {
        "minimum": 0,
        "type": "integer",
        "format": "int32"
      },
      "limit": {
        "minimum": 1,
        "type": "integer",
        "format": "int32",
        "example": 100
      },
      "skip": {
        "minimum": 0,
        "type": "integer",
        "format": "int32"
      },
      "order": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": ""
      },
      "include": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Include"
        },
        "description": ""
      }
    }
  }
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dougal83** [comment]
@bajtos Here is a [draft gist](https://gist.github.com/dougal83/92b1c5bcc05bd4835861246bc7196e4f).  I need to run code against samples and write tests(*sigh).

Where would be the best to place this code and where to inject it's functionality?  I'll put into PR for review pending your feedback.

**Comment by jannyHou** [comment]
@dougal83 commented in https://github.com/strongloop/loopback-next/issues/4290#issuecomment-569807646 :)

**Comment by bajtos** [comment]
After we land _feat(rest): add openapi schema consolidation_ #4365, I'd like to start the process of deprecating `getModelSchemaRef` and reworking both our existing code and CLI templates to leverage the new schema consolidation:

- Introduce `getModelSchema` similar to `getModelSchemaRef` (see [`src/controller-spec.ts`](https://github.com/strongloop/loopback-next/blob/1df8cd17f731a7af84284e0149e5d2749e6e3608/packages/openapi-v3/src/controller-spec.ts#L376-L382))
- Rework our controller templates to use `getModelSchema` instead of `getModelSchemaRef`
- Rework controllers inside `/examples` to use `getModelSchema`
- Soft-deprecate `getModelSchemaRef` in our documentation (both `/docs` files and the tsdoc comment)
- Update https://github.com/strongloop/loopback4-example-shopping to use `getModelSchema`

Considering the scope of that work, I think it may be better to open a follow-up issue. 

Thoughts?

**Comment by dhmlau** [comment]
Closing as done. Opened https://github.com/strongloop/loopback-next/issues/5791 as follow up issue.
