### ISSUE TITLE
Add bearer auth scheme as the default security scheme

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#4386]
## Suggestion

After story https://github.com/strongloop/loopback-next/issues/4380 finished, we can add a security spec enhancer to have the bearer auth scheme as the default(or built-in) security scheme. So that explorer has the authorization dialog for people to inject the token per request.

## Use Cases

Add an OAI enhancer that add the following spec into OpenAPI spec generated in the rest server:

```ts
"components": {
    "securitySchemes": {
      "jwt": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
```

## Examples

See the screenshot in https://loopback.io/doc/en/lb4/Authentication-Tutorial.html#specifying-the-security-settings-in-the-openapi-specification

## Acceptance criteria

- [ ] add a security spec enhancer to have the bearer auth scheme as the default(or built-in) security scheme

**Comment by dougal83** [comment]
Good idea to add to develop the schema.  Personally I'd be more specific and name it `jwt` rather than `bearerAuth`.

````json
      "jwt": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
````

**Comment by jannyHou** [comment]
@dougal83 ah, true `jwt` is more accurate 👍

**Comment by emonddr** [comment]
@dougal83 , @jannyHou ,

Regarding the comment

> Good idea to add to develop the schema. Personally I'd be more specific and name it jwt rather than bearerAuth.  

Exactly what are we talking about here?

The `title` of the github issue : 
`Add bearer auth scheme as the default security scheme` ?

Or

![image](https://user-images.githubusercontent.com/6864736/72074807-94d02500-32c0-11ea-99d7-e19e839e137a.png)

in https://loopback.io/doc/en/lb4/Authentication-Tutorial.html#specifying-the-security-settings-in-the-openapi-specification ?

Because the JSON examples above do not have 
`bearerAuth`

Please clarify.

Thanks

:)

**Comment by dougal83** [comment]
Hey @emonddr 

This issue is to enhance the openApi spec by adding to components.

I've just jumped on it to suggest a name change from `bearerAuth` to `jwt`.  I'm aware that `bearerAuth` is currently in use so if consensus for change is found then all instances would need to be updated.  The `bearerFormat` property is just arbitrary and so using `jwt` as security scheme name would be better IMO.

Considering the top level `security` property of openapi spec, it would be easier to grasp the nature without looking up the schema:

````json
  "security": [
    {
      "jwt": []
    }
  ],
````

Really me nitpicking atm.

**Comment by dhmlau** [comment]
@strongloop/loopback-next @strongloop/loopback-maintainers @mschnee 

Call for contribution: 
This task is part of the [epic "Allow out-of-box token based authentication in API Explorer" ](https://github.com/strongloop/loopback-next/issues/4391), that we wish to get it done in 2020Q1. If you're interested in working on it, please leave a message here and we'll assign it to you.  We'll take the first person who responds. 😬

Happy contributing!

**Comment by dougal83** [comment]
@jannyHou For clarification, is this story to add jwt strategy /w enhancer to base project generator template?

**Comment by dougal83** [comment]
I have a busy March so unassigned in case someone else wishes to help in the meantime.

**Comment by dhmlau** [comment]
@jannyHou @raymondfeng, could you please clarify? Thanks.

**Comment by jannyHou** [comment]
after having the jwt authentication component extracted in [examples/access-control-migration](https://github.com/strongloop/loopback-next/tree/master/examples/access-control-migration/src/components), I am thinking refactor the strategy in this example to extend the enhancer and provide jwt auth spec by default.

I am not sure if @raymondfeng still wants to have the authorize button enabled for explorer for ANY loopback app w/ or w/o authentication enabled. 

cc @raymondfeng WDYT?

**Comment by dhmlau** [comment]
@jannyHou, is it possible to show/hide the authorize button based on whether the app has authentication enabled? 
btw, what's the behavior in LB3?

**Comment by jannyHou** [comment]
<img width="1120" alt="Screen Shot 2020-03-12 at 2 33 44 PM" src="https://user-images.githubusercontent.com/12554153/76555851-d327c300-646e-11ea-95ae-7c58d6955f2f.png">

I created a LB3 app, disabled the auth system in boot script
>   // server.enableAuth();

The token field still exists in explorer so I believe it's always provided out of box in LB3.

**Comment by dhmlau** [comment]
How about we always show the authorize button, as the first iteration? It's better to always show the button/field than always hide! 

cc @raymondfeng

**Comment by jannyHou** [comment]
created PR in https://github.com/strongloop/loopback-next/pull/5493

**Comment by dhmlau** [comment]
Closing as done.
