### ISSUE TITLE
Relations with custom names not working

### ISSUE THREAD

**Issue by LonguCodes** [strongloop/loopback-next#4392]
## Steps to reproduce

Create a new Model with a property with belongsTo decorator and add name to definiton. Add relation to repository with the same name.

## Current Behavior

The relation is not created with the given name

## Expected Behavior

There would be a relation to the given name. If done using the default convention `relation name` + Id works as expected.

## Additional information

  linux x64 10.16.3
 ├── @loopback/authentication@3.2.4
├── @loopback/authentication-passport@1.0.6
├── @loopback/boot@1.6.0
├── @loopback/context@1.25.0
├── @loopback/core@1.12.0
├── @loopback/openapi-v3@1.10.3
├── @loopback/repository@1.16.0
├── @loopback/rest@1.25.0
├── @loopback/rest-explorer@1.4.6
├── @loopback/service-proxy@1.3.13
├── loopback-connector-mysql@5.4.2

**Comment by dhmlau** [comment]
@agnes512, could you please help? Thanks.

**Comment by agnes512** [comment]
@LonguCodes Hi, this is the limitation of our current design. We reject CRUD operations if the request body contains navigational properties. In your case, your source key and the relation name have the same name. It gets rejected when your request contains _the property name_. For example, when you create an instance with `{id: 1, name: 'my order', customer: 1}`, and your relation also named `customer`, it would recognize `customer` as the navigational property(i.e a `Customer` instance) instead of a property of model itself. So the current workaround is **not to use the same name for belongsTo source key and the relation name**.

Ref: [BelongsTo relation metadata](https://loopback.io/doc/en/lb4/BelongsTo-relation.html#relation-metadata), to customize your source key name in the source model for the belongsTo relation, this is what you need to do:

For example,  an`Order` belongsTo a `Customer`. The source key is `Order.customerId` and the relation name is `customer` by default.
I'd like to have the source key named `c_id` and the relation name as `myCustomer`. Since the source key defaults to the one decorated by the `@belongsTo` decorator, which is `c_id` in our case, we'd still need to specify the customized relation name:

```ts
export class Order extends Entity {
  @property({
    id: true,
    generated: true,
    type: 'number'
  })
  id: number;

  @belongsTo(() => Customer, {name: 'myCustomer'})
  c_id: number;
```

**Comment by LonguCodes** [comment]
Thanks for the help. It cleared up why i had problems before.
