### ISSUE TITLE
Jenkins Commit Linter clashes with Commit Sign-Offs

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4492]
## Steps to reproduce

1. Add a signed commit to a strongloop-community repo
2. Open a PR

## Current Behavior

Commit Linter will fail due to the commit sign-off. This can be problematic for repos that have a DCO instead of a CLA.

See: https://github.com/strongloop/explorer.loopback.io/pull/8

## Expected Behavior

The Commit Linter should be smart enough to exclude commit sign-offs from its line character count.

## Link to reproduction sandbox

N/A

## Additional information

N/A

## Related Issues

N/A

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@achrinza, discussing with @bajtos:
- the commit linter error occurs in the `explorer.loopback.io` because it has the linter rules of 50 characters on first line and 72 characters on subsequent lines, and uses DCO.  While most of our older repos are not using DCO, it might be a one-off issue. 
- there won't be much changes in that repo anyway, so I'd like to continue the reviews in https://github.com/strongloop/explorer.loopback.io/pull/8 and force push the PR when it's ready to land. 

Therefore, I'm closing this issue and continue our discussion on https://github.com/strongloop/explorer.loopback.io/pull/8. Thanks!
