### ISSUE TITLE
Guide: writing components

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#450]
Fill in content to https://github.com/strongloop/loopback-next/wiki/Writing-Components

See also https://github.com/strongloop/loopback-next/wiki/Using-Components

**Comment by ritch** [comment]
This content is a good start. We need to go deeper and be explicit on how to write a component. Especially defining what a Provider is, how it works and how you use them. This really tripped up Tetsuo when he was writing his logger component. He immediately started using `app.bind()`.

Given his feedback, I also think the app / request ctx is not so obvious to someone writing a component. We should mention that here. How to write a component that uses the request / response objects. He also fell into a trap of: I can write it this way and it works so why not do it this way? In this case he was instantiating a `Logger` object in the app constructor and using it in the sequence. Something that JavaScript almost encourages, but is really an anti-pattern in our plugin examples. Might be useful to review his code.

> Components should use constructor-level Dependency Injection to receive the configuration from the application.
We need to explain this in more detail. What is our short definition of DI (we link to this, but we should explain it here too in context of components). How does it work? How do you use it? Why is it important?

We also need to be very clear on what a Provider is. Right now we don't define it anywhere in the docs: https://github.com/strongloop/loopback-next/search?q=provider&type=Wikis&utf8=%E2%9C%93

In order to keep these sections brief, we can create additional sections for some of these places where we want to go deeper. Eg. where you linked to DI in my quote above.

Most of these comments above are movtivated by my experience explaining how to build components to folks, it might help to do the same and take note of the areas of confusion.

**Comment by bajtos** [comment]
@ritch thank you for the feedback. I edited the wiki page and incorporated a big part of it, see https://github.com/strongloop/loopback-next/wiki/Writing-Components. Could you please review?

@Setogit please read the new content too, I think it may give your better context for your work in https://github.com/strongloop/loopback-next/pull/484.

**Comment by bajtos** [comment]
I am closing this issue as done, we can open follow-up issues if there are any more improvements to be made.
