### ISSUE TITLE
Inspect application, controllers/routes, repositories and models

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#461]
See https://github.com/strongloop/loopback-next/issues/404#issuecomment-317785818

> (...) able to explore the entire App, similar to what we had in LB<4 app.models where you could iterate the models and scopes, etc....
>
> 1.- I've already put an effort on https://github.com/mean-expert-official/openapi-sdk-builder so we can build an SDK from the open-api spec... But that is too limited, more if $ref is not yet supported.
>
> I don't think I can achieve the same functionality we have in https://github.com/mean-expert-official/loopback-sdk-builder from the open api spec.
>
> 2.- Regardless the SDK, in order to rewrite FireLoop on top of LB4 by creating components https://github.com/strongloop/loopback-next/wiki/Using-Components, we need a way to explore the entire App, controllers, models, scopes and repositories from those components.

cc @jonathan-casarrubias

**Comment by bajtos** [comment]
Cross-posting my https://github.com/strongloop/loopback-next/issues/404#issuecomment-318024747:

One option that's already available in loopback-next is to inspect bindings matching a key pattern. For example, `app.controller()` is binding the controller class to `controllers.${controller.name}` under the hood. Repositories (representing models) are bound similarly.

On the other hand, the routes (even Controller-based ones) are registered directly with the http router/handler, therefore they are not inspectable via IoC context. However, I think it should be reasonably easy to expose an API allowing components to access the list of all registered routes. This list represents the exact REST API as it is exposed by the application.

Here is the code processing decorators (and other ways how to define HTTP routes) and setting up a http handler: [packages/core/src/application.ts#L102-L130](https://github.com/strongloop/loopback-next/blob/57a6e4ddd922514de332606d7d69668f2d20c875/packages/core/src/application.ts#L102-L130)

As I wrote earlier, I think it will be best to make routes inspectable, so that tools like the SDK builder can get a list of all HTTP endpoints, similarly to how LoopBack/strong-remoting 3.x allowed tools to get a list of all shared methods.

**Comment by jonathan-casarrubias** [comment]
@bajtos I really appreciate you taking the time to answer my thoughts and by creating this issue to address my concerns, I believe focusing in inspectability is key, therefore a new issue for that is the best Idea.

I agree with all of your comments and that gives me an idea of the development path so I can plan in this side, also clear the uncertainty for the many weekly questions I got about the LB4 refactor and how does that affect the SDK future or the FireLoop future.

Btw from the application.ts file you referenced, I like the `this.find('controllers.*')`method, I guess is what you are trying to explain, so a similar approach to inspect the entire application would be great.

About the 1:1 relationship between controllers and models / repositories I understand that, and my plans are to provide a real-time interface to access both

  1) A real-time controller interface, but also I'm planning to
  2) Expose Repositories (Former model references), through a similar -or the same if I can- interface that I currently provide with current FireLoop version

This way migration to LB4 will be easier for some simple projects it might work out of the box without rewriting anything, of course other more complex projects will need to migrate logic to controllers, and use the new real-time controller interface.

I will keep a more closer eye on this thread since it's critical to extend LB4, once this is landed I will start the refactor of fireloop on top.

cheers
Jon!
