### ISSUE TITLE
Remove CLI-generated `booterOptions`

### ISSUE THREAD

**Issue by achrinza** [strongloop/loopback-next#4672]
Currently, the lb4 `CLI` generates `booterOptions` in `application.ts`:

```typescript
// Customize @loopback/boot Booter Conventions here
this.bootOptions = {
  controllers: {
    // Customize ControllerBooter Conventions here
    dirs: ['controllers'],
    extensions: ['.controller.js'],
    nested: true,
  },
};
```

## Suggestion

`this.bootOptions.controllers` should be removed from the generated code as the default configuration is identical.

## Use Cases

Removing this configuration will remove the clutter in the CLI-generated code and make it easier for new developers to understand and utilize LoopBack 4.

A comment can be left directing developers to the documentation on how to configure `booterOptions` to prevent the feature from being obscured.

## Examples

N/A

## Acceptance criteria

TBD - will be filled by the team.

_Suggestion_
- [ ] Remove `booterOptions` config from [app generator template](https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/app/templates/src/application.ts.ejs)
- [ ] Update [Booting an Application](https://loopback.io/doc/en/lb4/Booting-an-Application.html) to include default values

**Comment by bajtos** [comment]
Hi @achrinza, thank you for opening this discussion.

My argument for introducing `this.bootOptions` was to make it easier for new developers to understand what is the default behavior and also learn how to customize conventions used by our bootstrapper (what options are available). Instead of having to read through (possibly long) documentation, users can immediately see all information right in their code.

Secondly: when the configuration is captured in the application constructor (even if it's the same as the current defaults), if we change the conventions (the default config) in a backwards-incompatible way in the future, existing applications will require very little changes to migrate, precisely because their conventions are configured by the app, not loaded from our bootstrapper.

If we agree with my argumentation, then instead of removing the current controller config, we should instead add default configuration for other booters that are included out of the box (datasource booter, repository booter, etc.)
