### ISSUE TITLE
Bring questions back to GitHub, use GG only for announcements

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#47]
Our new official policy is that questions are allowed on GitHub, at least until LoopBack4 reaches GA. Users are still encouraged to post their questions on StackOverflow though.

We should apply yellow "functional-area" labels like "CLI", "Examples", "Docs" to questions as part of our issue triage process. This will make it easier for people to find unanswered questions related to their area of interest/expertise.

(See also a follow-up issue to improve Contrib docs in general: https://github.com/strongloop/loopback-next/issues/950)

## Acceptance criteria

 - [x] Update our docs to reflect our policy change: http://loopback.io/doc/en/contrib/Reporting-issues.html.  Updated policy along the lines: 
```
<!--
HELP US HELP YOU BY
- Doing a quick search to avoid duplicate issues
- Providing as much information as possible (versions, use case scenarios for features, etc.)
- Open GitHub issue as the last resort
If you have a question then please consider using a more suitable venue:
 - https://stackoverflow.com/questions/tagged/loopbackjs
 - https://groups.google.com/forum/#!forum/loopbackjs
 - https://gitter.im/strongloop/loopback
-->
```

---

The original description from Simon for posterity:

Flame war topic.

Pros:
- Centralize developer activity to GitHub
- Easier to search/keep history centralized
- One place to maintain/manage instead of explaining to users (which goes along with our contributor first principle)

Cons:
- WIll inflate number of actual issues on GH
- Split history (but we don't have to remove old posts from GG, so it's sort of moot)

**Comment by bajtos** [comment]
@kjdelisle @raymondfeng @ritch @bajtos @superkhau 

 - we can gradually move Q&A to github, but keep supporting the mailing list too
 - we need to be more active in closing issues (especially questions), so that we don't have many stale open issues
 - should we use a different repository for Q&A to allow us to assign different permissions?

**Comment by virkt25** [comment]
I'm ok with the idea of letting users ask questions as GitHub Issues and definitely agree with need to be more proactive to close issues.

An obvious omission and a possible go to for most people imo is StackOverflow. Any reason that's not mentioned in this thread at all? Ask people to post questions there and tag them `loopback` and anyone can answer. GitHub to me is more a development tool and should be used as such. SO also ranks higher on Google than GitHub (from my experience, not verified). It just seems like the more appropriate place for Q&A. Having said that ... we don't need to have a hard rule saying no questions on GH. We can answer them here and say next time try SO. 

This is what `angular` says on their repo for questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by bajtos** [comment]
>An obvious omission and a possible go to for most people imo is StackOverflow. Any reason that's not mentioned in this thread at all?

> This is what angular says on their repo for questions:
> https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

This is the part that's not working well and we want to move away from it:

> To save your and our time, we will systematically close all issues that are requests for general support and redirect people to Stack Overflow.

Once people posted the question on GitHub, it's easier to answer their question right there, instead of asking them to re-post on StackOverflow, where we won't follow up with an answer.

I like how Angular is recommending people to use SO and explaining why it works better for questions, I am happy to adopts the same recommendation. Just note that the SO tag is [`loopbackjs`](https://stackoverflow.com/questions/tagged/loopbackjs).

> we don't need to have a hard rule saying no questions on GH. We can answer them here and say next time try SO.

I think that's a great solution, +1 from me.

**Comment by crandmck** [comment]
+1 from me as well on using SO as preferred forum for questions.

Even so, there will always be questions asked in GH, because:
- People will just ask questions there, regardless of what we tell them to do.
- Sometimes an issue that begins as a  "bug report" or "feature request" is really a question in disguise, either because the user misunderstands the behavior, due to a bug in product or docs, or a question comes up as a result of a workaround, etc.

So IMHO we just need to decide on a general policy or "best practice" for inevitable cases where people _do_ ask questions in GH issues.  Currently, the policy is to just close the issue and say "Ask in GG or SO".

IIUC the suggestion earlier in this discussion was to stop doing this, and answer the question directly in GH instead.   It wouldn't be _that_ much work to then cross-post the Q&A to SO, but it would add a small amount of additional work per question.  I think it should be left to the discretion of the answerer/team whether to do this, depending on how useful the Q&A would be to others.

**Comment by dhmlau** [comment]
IMHO.. Since we're using GitHub on a daily basis, it is easier to get our attention if questions are posted here than SO.  If we direct people to ask questions in SO, then we'll need to monitor that as well, which gives extra burden to everyone because answering questions in SO has been a best-effort basis so far for us. 

Perhaps GG, SO and gitter fall under "helping each other out in the community" category?  And we keep that as best-effort in terms of monitoring/answering questions there?

**Comment by virkt25** [comment]
+1 to just GitHub for us providing support to community. Just ask that questions be tagged appropriately (but no big deal if they aren't since we can add the tags).

**Comment by jannyHou** [comment]
People have different opinions for this issue, label it as needs-discussion. let's post comments here.

**Comment by dhmlau** [comment]
Summary of today's estimation meeting, we agreed that: 
- we should update http://loopback.io/doc/en/contrib/Reporting-issues.html so that we're not discouraging questions on GitHub
- the current github template can be simplified 
- updating doc and github template do not need to be tied to the same task
- we may not need a blog post to broadcast we're accepting questions. (people are posting questions in our github repos anyway!)
