### ISSUE TITLE
Table lock handling

### ISSUE THREAD

**Issue by AnanthGopal** [strongloop/loopback-next#4873]
Hi,
Normally table locked when we select the data from a  table, Consider my table have more records i get data from that TESTTABLE, so that i used below query
`Select * from TESTTABLE tt `
if i run above query, that testtable will be locking milliseconds, if i use below query, the table will not lock 
 `Select * from testtable tt for update of tt skip locked`
have this option in loopback?
i need to select the data without lock like `Select * from testtable tt for update of tt skip locked`

**Comment by achrinza** [comment]
AFAIK the official lb4 connectors only use run-of-the-mill SQL queries. Hence it's not possible unless a custom SQL query is executed using `.execute()`.

Though since it's the responsibility of the connector to provide this functionality, the answer may vary depending on which connector is being used.

**Comment by emonddr** [comment]
@AnanthGopal, have you tried what @achrinza has suggested?

**Comment by AnanthGopal** [comment]
yes That's working
