### ISSUE TITLE
core: support configurable openapi URLs

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#488]
Allow application developers to customize the URL where application's openapi spec is served (current hard-coded default: `/openapi.json`).

See https://github.com/strongloop/loopback-next/pull/475#discussion_r130181575

**Comment by raymondfeng** [comment]
To serve OpenAPI spec with LB.next will be a good a validation for the following perspectives:

1. Allow a component (openapi explorer component) to serve certain routes
2. Support content negations based on `Accept` header and other information so that we can render OpenAPI spec in v2, v3, json, yaml etc. 
3. Enable CORS

**Comment by bajtos** [comment]
Removing from 4.0 GA to "Further rest layer improvements" epic (#1452).
