### ISSUE TITLE
[GSSC-GVT]The help menu seems displays the same when input different LB4 command.

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5119]
Steps:
1. Input command: apic lb4 example -h 
check the screen1;
2. Input command: apic lb4 -h 
check the screen2;
screen1
![image](https://user-images.githubusercontent.com/45190559/79431252-c31a7a80-7ffc-11ea-9802-6fc4b58306a5.png)
screen2
![image](https://user-images.githubusercontent.com/45190559/79431365-ee9d6500-7ffc-11ea-9fea-590f65734a4c.png)

Actual Result:
The help messages are the same when input different lb4 command for help

**Comment by dougal83** [comment]
I believe the `-h` flag outputs out a static message and there is no support for each command.  Perhaps as part of revisiting the cli code this feature could be addressed? See #844

**Comment by agnes512** [comment]
This should be fixed by https://github.com/strongloop/loopback-next/pull/5126. Closing as done.

**Comment by agnes512** [comment]
@wxuwh  I think `-h` and those options can be applied to all commands. So the first ones are the same, and the rest content should be different ( see the screenshots below). I also notice in those pics that you have the same usage for both commands:
```
lb4 app [<name>] [option]` for those two commands. 
```

I checked locally, they have correct display on my end: 
#### lb4 -h
![image](https://user-images.githubusercontent.com/50331796/80024693-75df5280-84ad-11ea-9206-70165c376e1a.png)

#### lb4 example -h
![image](https://user-images.githubusercontent.com/50331796/80024733-8394d800-84ad-11ea-93fa-36f1288a3d05.png)

You might want to check if you have the latest CLI installed. 

Some characters are mixed in `help`, `skip-cache`, etc. to show that they are translatable. 

I am closing the issue as it is the expected behavior. Feel free to reopen it if you have question, thanks!
