### ISSUE TITLE
loopback-next-hello-extension sample package

### ISSUE THREAD

**Issue by Setogit** [strongloop/loopback-next#532]
purpose: example code come along with extension blog post: task #524
refactor `loopback-next-hello-world` so that the two work seamlessly.

**Comment by bajtos** [comment]
In this sprint, as part of #525, @virkt25 will be working on `loopback-next-hello-extension` project aiming at new extension developers.

I think this issue is mostly a duplicate of #525, but let's keep it open in case the blog post have different needs and some tweaking of loopback-next-hello-extension is needed.

**Comment by dhmlau** [comment]
closing as duplicate of #525.
cc @virkt25
