### ISSUE TITLE
docs: Schemas

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#554]
Create a new wiki page to provide documentation about schemas.

 - What is a Schema?

 - How to:

   - Define a schema for a route response
   - Define a model with a schema

**Comment by crandmck** [comment]
Created stub page as placeholder: https://github.com/strongloop/loopback-next/wiki/Schemas

**Comment by bajtos** [comment]
Describe the current status (two flavours of schemas - REST API/OAI, juggler models), point to existing content (swagger spec, loopback.io docs for models).

Mention future plans to unify these two schemas and/or add tooling to make it easier to keep them in sync.

**Comment by kjdelisle** [comment]
I have strong concerns about how the decorators are using typeless JSON input to provide type data.

The example we're currently using:
```ts
@model()
export class Product extends Entity {
  @property({
    type: 'number',
    id: true,
    description: 'The unique identifier for a product',
  })
  id: number;

  @property({type: 'string'})
  name: string;

  @property({type: 'string'})
  slug: string;

  constructor(data?: Partial<Product>) {
    super(data);
  }
```

If we intend to reuse the Entity class for the "new Juggler" (in whatever form it takes), then we're losing the strong-typing we get from using TypeScript to immediately fall back on the untyped metadata that powers LoopBack 3.



The greater consequence of this is that we'll have to rebuild a whole new validation engine that works the _exact same way_. Even though TypeScript will make it easier for us to build this validation engine, it will provide no additional value or direction to the user when they go to _make use of that engine_!

They'll be stuck with the same use-case they currently have, where they need to guess-and-check their types, relationships, etc. when building their LoopBack applications.

We should be parsing the decorated classes for their property types based on the decorator's presence and leveraging the provided types at that point rather than asking users to re-provide that information in text form.

```ts
@model
export class Product extends Entity {
  // @id should be a special case of @property, so don't redeclare it.
  @id
  @description("The unique identifier for a product.")
  id: number;

  @property
  name: string;

  @property
  slug: string;

  constructor(data?: Partial<Product>) {
    super(data);
  }
```

**Comment by raymondfeng** [comment]
Once we have the schema for `PropertyDefinition`, we can define TS interface as the type to be accepted by `@property()`.

**Comment by kjdelisle** [comment]
I don't understand how this helps; it would be a type that would convey the type information of the object in an _untyped fashion_; it's just a type that carries the untyped validation.

**Comment by raymondfeng** [comment]
For example, if `@property` takes https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/model.ts#L22, TS will check the interface compatibility for the property json value.

**Comment by kjdelisle** [comment]
https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/model.ts#L23
The problem I have with this, is that one of the valid examples is "string". Which is why I'm confused as to how it solves the problem of needing to build a type inference system that parses those strings to determine what the corresponding type is of things like "string", "number", "Foo", "TotallyMadeUpTypeIDidNotDefineInMyConfig", and so on.

**Comment by raymondfeng** [comment]
If you refer to the `type`, we (between @bajtos and myself) already discussed to possibility to leverage TypeScript design-time metadata so that the decorator can infer the `type`.

**Comment by bajtos** [comment]
> the problem of needing to build a type inference system that parses those strings to determine what the corresponding type is of things like "string", "number", "Foo", "TotallyMadeUpTypeIDidNotDefineInMyConfig", and so on.

AFAIK, the type inference provided by TypeScript recognizes only the type values supported by `typeof` operator. This means that types like `Date`, `RegExp`, `Foo`, `PersistedModel` etc. are all reported as `object`, at least that was the case when I last checked.

As for the decorators, I believe they are not using typeless JSON input - the input value is described via TypeScrip interface, which for example means that VS Code is able to offer suggestion for property names. See https://github.com/strongloop/loopback-next/blob/06c787b01992c878b5aafb25a53c2cdbbeb5df42/packages/repository/src/decorators/model.ts#L54 and https://github.com/strongloop/loopback-next/blob/06c787b01992c878b5aafb25a53c2cdbbeb5df42/packages/repository/src/model.ts#L19-L28

Yes, we cannot verify that the `type` field in `@property` JSON data matches the type of the underlying TypeScript property, but as I wrote, I believe this is a limitation of TypeScript language. 

> We should be parsing the decorated classes for their property types based on the decorator's presence and leveraging the provided types at that point rather than asking users to re-provide that information in text form.

This is an interesting idea. IIUC, you are proposing to write a TypeScript pre-processor that will parse the source into AST, traverse that tree and build a better understanding of the model classes? One important limitation is that we cannot do that at runtime, only at build/compile-time, but I guess that's ok, because TypeScript is all about build/compile-time.

**Comment by dhmlau** [comment]
@bajtos, for the `[attribute: string]: any` from this snippet: https://github.com/strongloop/loopback-next/blob/06c787b01992c878b5aafb25a53c2cdbbeb5df42/packages/repository/src/model.ts#L19-L28 
Are we planning to support the complete list in [LB3](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#properties)?  I guess it won't matter until we have the declarative support in GA?

**Comment by dhmlau** [comment]
@kjdelisle , thx for picking up this task.  Here is my incomplete changes: https://gist.github.com/dhmlau/60906df54063fff1ffd61bca5596401f

**Comment by bajtos** [comment]
>  for the [attribute: string]: any from this snippet:
> Are we planning to support the complete list in LB3?

I think @raymondfeng is better suited to answer this question, but as long as we are using current (legacy) juggler under the hood, I think we should support all LB3 metadata for property definitions.

Also note that `json` and `store` metadata is not supported in the current implementation AFAIK, I think it's something that Raymond would like to eventually see in the framework.

**Comment by kjdelisle** [comment]
The docs are merged!
