### ISSUE TITLE
Memory Leak caused by destroy() not being called for debug() instances created by various loopback packages

### ISSUE THREAD

**Issue by mpohjola-fidera** [strongloop/loopback-next#5943]
## Steps to reproduce

1. Load a loopback 4 project. I Used[ loopback4-example-todo](https://github.com/strongloop/loopback-next/tree/master/examples/todo) to successfully replicate the issue. 

2. Start project (with inspector to see the issue). For example `NODE_ENV=production && node --inspect dist/index.js ` Setting the `NODE_ENV` to production is optional in reproducing the steps.

3. Use any chosen method to simulate large amounts of traffic to server. I used Siege as my tool of choice. 
For example: `siege --concurrent=10 --reps=2500 --content-type="application/json" 'http://localhost:3000/todos'`

## Current Behavior

There are multiple `debug()` instances (with the same namespaces) retained by `createDebug()` closure. 
It seems likely that an amount of debug() instances are created for each request (and never destroyed) causing incremental memory usage. 
The instances are very small making the bug hard to detect under light load, but we have witnessed the `instances` array under `createDebug()` to incrementally grow to over 200000 entries (while consuming around 74mb of memory (49 % of memory used by the application at the time) in our test environment. In time the memory leak grows significant enough to cause application to slow down and crash.

Example of bug reproduction done on top of the `loopback4-example-todo` project:
![createdebug-instances-array-bloat-1](https://user-images.githubusercontent.com/49230582/87660737-3a7cb900-c768-11ea-8881-8bc1744f9cae.png)

In the above example we have sent three sets of 10000 GET requests on the server and you can clearly see how the `instances` array under `createDebug()` has severily bloated.

Additionally in this second picture you can see the large amount of objects retained between snapshots 2 and 3. In this case there is one `debug()` created and retained per request:
![createdebug-instances-array-bloat-2](https://user-images.githubusercontent.com/49230582/87660751-3ea8d680-c768-11ea-8256-e24c247f9294.png)

The problem seems worse in more complex applications where there are more than one `debug()` instance created for each request.

## Expected Behavior

`debug()` instances should be cleaned from memory (for example by calling `destroy()` on them). A possible midway solution could be that the debugging would not be enabled in production (now the `debug()` commands are called regarding the environment).

## Additional information

This issue seems to be related to known memory leak bug in [debug ](https://github.com/visionmedia/debug)library  (https://github.com/visionmedia/debug/issues/678 ) in which `debug()` instances are retained in memory if explicit `destroy()` is not called for them and the bedug library is utilized in some specific manner.  There is a fix planned for the issue in debug library but it seems unlikely that it would be published any time soon as the issue regarding the leak has been open since January 2019.

We were able to circumvent the issue for now by forcing all loopback packages our application depends on to use a branch version of the debug library which has the proposed fix for the leak ("visionmedia/debug#no-leak"). But this is of course not a good long term solution and it would be much preferable if the usage of debug library would be fixed in loopback packages.

The bug likely affects all loopback applications but is most prominent on applications that receive larger amounts of traffic.

**Comment by bajtos** [comment]
Thank you @mpohjola-fidera for reporting the issue.

I suspect the problem was introduced by https://github.com/strongloop/loopback-next/commit/f651e5be28efe624e83a7139152ed00554580dca, where a per-context-instance `debug` instance was implemented.

Could you @mpohjola-fidera please verify if versions of `@loopback/context` older than `3.4.0` are showing the same problematic behavior?

>  `debug()` instances are retained in memory if explicit `destroy()` is not called for them

Hmm, this is tricky because JavaScript does not allow classes to provide a finalizer (a `destroy`) method that would be called by GC when a class instance is collected for garbage collection.

As I understand `debug`, it's meant to be used as a per-module or per-source-file singleton. Creating a new debug instance per Context instance is probably a bad idea. Quoting from visionmedia/debug#678: _This isn't a typical use-case for debug._

It makes me wonder if we can rework our context debug logging from per-context-instance loggers (app, request 1, request 2, etc.) to per-context-class loggers (Application, RequestContext).

@raymondfeng WDYT?

**Comment by raymondfeng** [comment]
@mpohjola-fidera Great catch. Can you try https://github.com/strongloop/loopback-next/pull/5948?
