### ISSUE TITLE
Add a new decorator `@visibility('undocumented')`

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#6392]
#1896 added support for a LoopBack-specific OpenAPI metadata allowing API developers to hide an endpoint (an OpenAPI operation) from the spec generated by the server.

```json
{
  "x-visibility": "undocumented"
}
```

~~At the moment, developers must use `@operation` decorator to provide this metadata, decorators like `@get` and `@post` cannot be used.~~

Let's implement a new decorator `@visibility` to make it easier to add `x-visibility` metadata to controller methods.

Example use:

```ts
class MyController {
  @get('/')
  @visibility('undocumented')
  index() {
     return '<html>Undocumented internal endpoint.</html>';
  }
}
```

**Comment by achrinza** [comment]
> Let's implement a new decorator `@visibility` to make it easier to add x-visibility metadata to controller methods.

+1 for adding the decorator. It helps abstract OAS 3 away from the developer, thereby making it more discoverable and more "natural" to implement. Let's make the decorator applicable at the `controller` level too, similar to [existing OAS decorators](https://loopback.io/doc/en/lb4/Decorators_openapi.html#oasdeprecated).

>At the moment, developers must use `@operation` decorator to provide this metadata, decorators like `@get` and `@post` cannot be used.

The [documentation](https://loopback.io/doc/en/lb4/creating-components-rest-api.html#undocumented-endpoints) states otherwise:

![image](https://user-images.githubusercontent.com/25147899/93733647-c4ce1700-fc08-11ea-86e0-1b9bd74560c2.png)

**Comment by bajtos** [comment]
> +1 for adding the decorator. It helps abstract OAS 3 away from the developer, thereby making it more discoverable and more "natural" to implement. Let's make the decorator applicable at the `controller` level too, similar to [existing OAS decorators](https://loopback.io/doc/en/lb4/Decorators_openapi.html#oasdeprecated).

+1
 
> > At the moment, developers must use `@operation` decorator to provide this metadata, decorators like `@get` and `@post` cannot be used.
> 
> The [documentation](https://loopback.io/doc/en/lb4/creating-components-rest-api.html#undocumented-endpoints) states otherwise:

Ah, my bad, thank you @achrinza for correcting my mistake!
