### ISSUE TITLE
Restyling the sidebar to distinguish app and extension experience

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#6477]
A follow up story of https://github.com/strongloop/loopback-next/issues/5785

## Suggestion

Refactor the sidebar to distinguish between app and extension experience. Please read the discussion in https://github.com/strongloop/loopback-next/issues/5785 to know more about how to customize the menu items.

**A summary of the new sidebar**:

```
- OVERVIEW
- GETTING STARTED
- INSIDE A LOOPBACK APPLICATION (rename to PREVIEWING A LOOPBACK APPLICATION?)
+ CONCEPTS (rename to UNDERSTANDING LOOPBACK 4 CONCEPTS?)
+ BUILDING APPLICATIONS
    + TUTORIALS
    + HOW-TO GUIDES
+ EXTENDING LOOPBACK 4
    + TUTORIALS 
    + HOW-TO GUIDES (most of contents in https://loopback.io/doc/en/lb4/Extending-LoopBack-4.html will be moved here)
    - COMMUNITY EXTENSIONS
+ BEST PRACTICES
+ REFERENCE GUIDE
+ CONTRIBUTING TO LOOPBACK 4
-  FAQ
+ MIGRATION GUIDE
```

Implementation tips:

- If we create nested menu, "BUILDING LOOPBACK 4 APPLICATION" and "EXTENDING LOOPBACK 4" must NOT collapse. 
- Consider using metadata like `{collapse:  true}` to configure the menu.
- Consider using separator instead of nested menu to distinguish the app vs extension content. It shouldn't be hard to test the 2 proposals, see which one looks better.
   ```
    // separator
    BUILDING LOOPBACK 4 APPLICATION
    + HOW-T0 GUIDES
    + TUTORIALS
    EXTENDING LOOPBACK 4
    + HOW-TO GUIDES
    + TUTORIALS

    // nested menu
    + BUILDING LOOPBACK 4 APPLICATION
       + HOW-T0 GUIDES
       + TUTORIALS
    + EXTENDING LOOPBACK 4
       + HOW-TO GUIDES
       + TUTORIALS
   ```

## Acceptance criteria

- [ ] Refactor the sidebar according to the snippet above.
- [ ] Make sure when visit from phone it displays as well.

**Comment by bajtos** [comment]
Few comments to consider:

(1)
Personally, I feel "COMMUNITY EXTENSIONS" don't belong to "EXTENDING LOOPBACK 4" because they have different target audience.

- "COMMUNITY EXTENSIONS" is for people building applications and looking for a recommended solution for a requirement they have, they are looking for an existing extension. For example, how to implement soft-delete. 

- "EXTENDING LOOPBACK 4" is for people who want to build a (new) extension, e.g. by extracting some reusable parts from their app.

In that light, maybe we can nest "COMMUNITY EXTENSIONS" under "BUILDING LOOPBACK 4 APPLICATION"?

(2)
I find the name a bit long "BUILDING LOOPBACK 4 APPLICATION". Can we use something shorter, e.g. "BUILDING APPLICATIONS"? 

(3)
Regardless of the title we choose, I think it should use plural "APPLICATIONS", not singular "APPLICATION".

I think these are rather minor details, we can discuss them during pull request review process.

**Comment by jannyHou** [comment]
@bajtos thanks!

For (1), I don't have a strong opinion for it, but since the title contains "EXTENSIONS", I feel it's consistent with the topic "EXTENDING LOOPBACK 4". Actually, essentially extending LB4 is also for building applications. Let's discuss in the PR when it's ready :)

For (2) (3), 👍 "BUILDING APPLICATIONS" sounds good.

**Comment by mdbetancourt** [comment]
talking about the sidebar what about to changes the style that menu is a little ugly for example https://github.com/onury/docma is pretty cool (unfortunately is not maintained anymore)

**Comment by jannyHou** [comment]
Follow-up stories: Add separate pages for building application and extending loopback 4. Those 2 pages should contain high level descriptions, instead of being just a link.

Tips: 
Building app: 
- possibility to build app kinds of apps
- how a lb4 app could be: from different perspective : rest/boot/service-proxy/non-rest

**Comment by jannyHou** [comment]
@mdbetancourt Sorry for replying late. Good suggestion 👍 unfortunately, I am afraid we don't have the bandwidth to update the website's theme 😞 features+bug fixes have higher priority than the front end change.

**Comment by jannyHou** [comment]
Closing as PR merged.
