### ISSUE TITLE
Peer dependencies are unnecessarily updated

### ISSUE THREAD

**Issue by nflaig** [strongloop/loopback-next#6546]
Currently peer dependencies are unnecessarily updated by lerna. For example if you are using `@loopback/booter-lb3app` and you are updating your packages to latest minor versions, it might happen that you suddenly get the warning that it requires another major version of for example `@loopback/rest` as peer even though nothing really changed in `@loopback/booter-lb3app`.

This should not be the intended behavior in my opinion as the peer dependency should have the minimal required version of the package.

## Current Behavior

Peer dependencies are unnecessarily updated in `chore: publish release` commits

## Expected Behavior

Peer dependencies should only be updated if it is really required

## Further notes

I think managing peer dependencies with only `^` will not properly work, it sometimes is required to use for example `>=1.0.0` or even `>=1.0.0 <3.0.0`, looking at the currently available packages using `>=` with the minimum required version would be the best solution as far as I can see.

**Comment by raymondfeng** [comment]
@nflaig We discussed this issue in the past. As you pointed out, it would be ideal that we can support a wider range of compatible versions for `peerDependencies`. 

But it's really hard to have CI to cover such combinations. We decided to take a conservative approach to update `peerDependencies` so that `@loopback/*` packages will be guaranteed to work with their peers in the same release, which can be upgraded together with `lb4 update`.

**Comment by nflaig** [comment]
@raymondfeng Thanks for letting me know. I already assumed the points you mentioned and I also don't see a good solution for it besides manually maintaining peer dependencies. An interesting side-effect to this is that it also "forces" users to update to latest package versions which is not a bad thing in general.
