### ISSUE TITLE
page not found when click on try it out

### ISSUE THREAD

**Issue by smartmouse** [strongloop/loopback-next#6704]
click on try it out
<img width="738" alt="Screen Shot 2020-10-31 at 11 55 34 PM" src="https://user-images.githubusercontent.com/4519627/97794809-eb527b00-1bd4-11eb-8384-aaa598569374.png">
<img width="1467" alt="Screen Shot 2020-10-31 at 11 53 47 PM" src="https://user-images.githubusercontent.com/4519627/97794811-f4dbe300-1bd4-11eb-9fe0-5c904fef64df.png">

**Comment by dougal83** [comment]
Hi @smartmouse,

Is this on [https://loopback.io/doc/en/lb4/Authentication-tutorial.html](https://loopback.io/doc/en/lb4/Authentication-tutorial.html) ?  Can you confirm that the link is the item on the Page Contents list and that it is still broken for you?  I've had a look and that link is working for me.

**Comment by achrinza** [comment]
The issue is in the [README}(https://github.com/strongloop/loopback4-example-shopping/blob/649394b420f78d5deeeceae55b23331e5af6399f/README.md#tutorial). Probably caused when we normalized the URL scheme to hyphenated PascalCase. Opened https://github.com/strongloop/loopback4-example-shopping/pull/918 as a fix.
