### ISSUE TITLE
unable to import "generateUniqueId" from @loopback/core

### ISSUE THREAD

**Issue by pktippa** [strongloop/loopback-next#6767]
## Steps to reproduce

As per the [Binding documentation](https://loopback.io/doc/en/lb4/Binding.html):

```ts
import {generateUniqueId} from '@loopback/core';
```

## Current Behavior

```
import generateUniqueId
'generateUniqueId' is declared but its value is never read.ts(6133)
Module '"../node_modules/@loopback/core/dist"' has no exported member 'generateUniqueId'.ts(2305)
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by achrinza** [comment]
This is usually caused by a dependency or the project requiring a newer version of `@loopback/core`.

Please do the following:
1. Backup the project
2. Test the backup
3. Update the CLI:
    ```
    npm i -g @loopback/cli
    ```
4. Update the project dependencies:
    ```
    // Run this at the project root
    lb4 update
    ```
5. Fix issues caused by breaking changes (if any)
6. Run the application

**Comment by achrinza** [comment]
Apologies, please ignore my previous comment; I was able to identify 2 issues:

1. The exports of `unique-id.ts` were not re-exported in `index.ts`
2. `generateUniqueId` is flagged as an `@internal` API.

I've opened #6771 to fix the first issue. As for the 2nd issue, I think it can be a separate discussion. @bajtos, since you introduced that portion of the docs, do you think we should keep the API level as `@internal`?

A workaround is to import is as follows:

```typescript
import {generateUniqueId} from '@loopback/context/dist/unique-id';
```
