### ISSUE TITLE
Deployment for production server

### ISSUE THREAD

**Issue by mbnoimi** [strongloop/loopback-next#6895]
## Suggestion

I suggest enhancing `package.json` for deploying a ready to go production distro.

## Use Cases

Deploying `dist` folder to VPS / Dedicated Server.
Currently, the developer must modify `package.json` by adding a script to be able to run `dist` folder correctly (see the discussion in [this link](https://stackoverflow.com/a/63750682/2015609))

## Acceptance criteria

TBD - will be filled by the team.

**Comment by achrinza** [comment]
As per-the StackOverflow answer, the default LB4 apps only require `dist`, `package.json` and `package-lock.json`. Is there a specific blocking issue?

**Comment by achrinza** [comment]
The solution above should be suffice for production environments that have prebuilt LoopBack 4 artifacts. For production environments that want to build on deploy, `npm start` would be the go-to command.

We'll proceed to close this issue but continue to monitor for replies. If you believe the solution above isn't suffice, feel free to comment what may have been missed and why, so that we can re-open the issue.
