### ISSUE TITLE
[OpenAPI] Loopback Artifact Generation

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#739]
## Goal

Determine how to map OpenAPI v3 spec into loopback artifacts.

## Questions
- [ ] Are there any libraries that will parse the entirety of OpenAPI spec files into TypeScript objects (that represent its format in code)
- [ ] Are there any existing tools to convert OpenAPI/JSON Schema/etc into TypeScript source code?
- [ ] Is it easier to create models as types, interfaces or classes when generating the TypeScript?
- [ ] What is required to:
  - convert the routes into controllers
  - convert the parameters into methods
  - convert the schemas from "components/schemas" into (types/interfaces/classes)

Please provide the results of the spike in a format that matches the questions above (to make sure we actually have our answers!)

**Comment by jannyHou** [comment]
I created a repo for the spike: https://github.com/jannyHou/spike/tree/openapi
It contains the spike result in `README.md`, and a sample app in https://github.com/jannyHou/spike/tree/openapi/app

**Comment by jannyHou** [comment]
Please check the spike in PR https://github.com/jannyHou/spike

**Comment by jannyHou** [comment]
@strongloop/sq-lb-apex @bajtos @raymondfeng  Thank you for all the reviews in https://github.com/jannyHou/spike/pull/3, appreciate your time and feedbacks !🎄, I am still replying to more.

Just putting down some notes so we can plan it in the meeting tomorrow:

As you may feel, it's too early to make a concrete plan for the top-down parsing, and also hard to settle down everything in one story, it's a pain for both the writer and reviewer. So I suggest we break down the topics we covered in this spike into sub stories, start to implement some basic and simple ones and at the same time keep discussion for the complicated ones. 

IMO we can start with creating a new openapi module, please note the module SHOULD NOT include context manipulation:

- Define types for openapi3 spec
  - should be similar to the swagger2 version: https://github.com/strongloop/loopback-next/tree/master/packages/openapi-spec
  - we can import them from [openapi3-ts](https://github.com/metadevpro/openapi3-ts/blob/master/src/model/OpenApi.ts) or create our own
    - short term: use community lib
    - long term: we may want to maintain types as our own code? They are quite basic and important
  - do we want to keep it a separate module or merge it into the new openapi module that contains decorators?
    - option1: separate module
    - option2: part of new openapi module
- Extract existing operation decorators from rest server module to a new openapi module
  - we may add more decorators in the future to specify a controller function's behavior, like @response, I assume [this issue](https://github.com/strongloop/loopback-next/issues/436) is a prove that users have that requirement. 
- Extract existing specgen functions for controller constructor as well

People seem all agree on the above ones, so we can start to work on them to give the following features a clean code base:

*We already have some discussion for them in this spike, I will move the discussion to proper stories*

- Create model decorators: Let's keep discussion in https://github.com/strongloop/loopback-next/issues/700, I will move people's opinions to that issue later. 

- Top-down parsing, well now I prefer to use "codegen" to describe the parsing and conversion from openapi spec to loopback representations. Some key points:
  - shall we keep it as a separate module from the openapi module? I feel yes
  - we only do openapi3 codegen, if user provides a swagger2 yaml file, we convert it to openapi3 first.
  - paths with same tag should be orginazed under one controller
    - where and how do we store `pathSpec` for each path, a combination of decorator and oas metadata
    - content-type
    - extensions: ^x-
  - where and how do we store oas resources(mostly components)
  - convert schema to model

**Comment by jannyHou** [comment]
I am moving all discussion under this issue instead of the PR in a personal spike repo:


@virkt25 Thank you for the feedback, for your questions in https://github.com/jannyHou/spike/pull/3#pullrequestreview-81351307

> I'm not sure I understand the scenario of multiple OAS files in 1 app

I think my point is adding another level to gather the OAS info that a server needs, so for example, if we have 3 rest servers in one app, 2 of them share the same resourceSpec and the 3rd one consumes another resourceSpec, then we can create two `oas`, register resourceSpec to `oas` and register `oas` to server instances. But seems people don't think it's necessary or a good approach, we still register resources to a server, and we also agree on not touching context in the OAS module.

> OAS Spec defines a server as a URL for the server. I don't think this has an implication for us since we're creating a microservice and have no control deployment.

Actually the openapi server spec could be more complicated then one URL, I simplify the scenario as an URL because our rest server currently calls `http.createServer()` to get a server instance, which has only one port and one domain. Does it answer your question or I maybe misunderstand your concern?

> do we keep the original file in the top-down approach or does the generator move the metadata into appropriate decorators ... creating it's own spec at runtime

- we DO NOT keep the original file
- I would say a combination of moving into proper decorator & keeping them as pieces in proper files
  - for the specs we have loopback representation for, like paths ---> controller, we can move then into decorators
  - for those component specs, there is no decorator yet...

> Is it not possible to support nested $ref

- For `path.parameters`, we have to resolve the whole `parameter` object without any reference to **generate the function**, BUT when moving the parameterSpec to `@operation()` decorator, we still keep it with `$ref` to make sure those reusable resources are still reusable
- By "resolving first level $ref", it's for the schema specifically, and I feel I should not use the word "resolve" here, let me explain it with an example:

```
"Pet": {
	"type": "object",
	"allOf": [
		{
			"$ref": "#/components/schemas/NewPet"
		},
		{
			"required": [
				"id"
			],
			"properties": {
				"id": {
				    "type": "integer",
			        "format": "int64"
                },
                "name": {
                    "type": "string"
                }
	        }
	    }
    ]
}
```

after the schema --> model conversion, the model file would be:

```js
// here we import `NewPet` instead of keep it as "#/components/schemas/NewPet",
// but we don't expend those properties in model `NewPet`
import { NewPet } from './new-pet.ts';
import { allOf, OASConfig, OASConfigType } from '@loopback/OAS';

export class Pet extends Model {
    @allOf('default')
    id: number
    @allOf('default')
    name: string
    @allOf('newPet')
    newPet: NewPet
    @OASConfig
    static OAS_config:OASConfigType = {<some_oas_metadata>}
}
```

**Comment by jannyHou** [comment]
I am closing this spike story and let's move those discussion to proper implementation stories.
In terms of spike, we already know what we are missing and what TBD for a top-down artifacts generation, while keep discussing everything in one story would be messy and eventually people cannot focus on making any decision.
