### ISSUE TITLE
This Project deserve a cooler name other than LoopBack

### ISSUE THREAD

**Issue by yshing** [strongloop/loopback-next#757]
Dear guys,

Thanks so much for building and maintaining the LoopBack project.

And this loopback-next project looks so cool and so different than the old LoopBack, which is pretty much a Full-Armor Express.js, super easy to work with for ppl experienced with Express.js.

This project is so much cooler and in fact having a fundamentally different architecture, philosophy and target audience  comparing old LoopBack is it possible for this Project to have a cooler name other than LoopBack?

Personally would be feeling very very graceful if this Project a better name than LoopBack.

# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

A better and cooler name.

# Additional information

**Comment by SippieCup** [comment]
I disagree. Loopback is an awesome name and perfectly describes the project as well.

Heres the definition of the word loopback:

> Loopback refers to the routing of electronic signals, digital data streams, or flows of items back to their source without intentional processing or modification.


That is exactly what the Loopback project aims to do at its core. Its an API that abstracts away all the processing that is required to routes a client input back to a data source. 

And not just one data source, but **any data source you want without any additional code** . You can put something in memory, or into Mongo, or MySQL, or Postgre, or another REST API, or _anything_ else without needing to learn and write the queries in a different langauge, or handle opening/closing connections, or anything at all. 

It all just works - without any intentional processing. 

it's LoopBack.

**Comment by yshing** [comment]
@SippieCup Although the goal is somewhat similar, the architecture and the path taken is extremely different.

http://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html

Due to the Architectural Change this project, loopback-next should not the same software as Loopback 1, 2, 3. 

In previous versions, Loopback it self is an express app and Rest is just a middleware.
In this version, `HttpServer` is part of the `RestServer`.

Which means the way you how you can really use LoopBack is totally different.

All the current code example for LB 1,2,3 won't work at LB-next.

Keeping the Project name Loopback means eventually you would concern on the Migration from old versions somehow, which looks pretty much a Mission Impossible.

Loopback 1, 2, 3 -> Loopback 4 share less common than Angular 1 -> Angular 4.

Migration from 3 -> 4 is not a sane idea at all, it requires a totally different mindset.

Keeping the name Loopback treats ppl into thinking LB 1, 2, 3 and 4 are 

Giving this project a name like e.g. `API-CORE` or `API-CORE a.k.a LB4` is much better than just naming it `Loopback 4`.
- Much more straight forward, no dictionary quote needed.
- API-Connect => API-Core.  api-connect-api-core, very illustrative. 
- Would not make ppl think you can migrate from previous version somehow and expect everything to just work.
- All the docs, and old coding example or stack-overflow questions would not get ppl confused.

But, there are already a module with that name and similar goal... 
https://github.com/ajuhos/api-core

**Comment by todrules** [comment]
I think completely changing the name would be a mistake because of the name recognition alone. Plus, I'm sure the SEO/marketing value of an established brand has quite a bit of value as well that you don't want to squander away.

However, I do see your point. Maybe they could add a 2nd term after Loopback to differentiate it somehow. Something like 'Loopback Voltage' or 'Loopback to the Future'. Or, hopefully, something much better than my suggestions. :)

**Comment by yagobski** [comment]
@todrules   Loopback next

**Comment by jpventura** [comment]
@yshing @yagobski Möbius

**Comment by arash01** [comment]
What about Loopback Plus, X, S or SE ?! (joking)

I would say Loopback Next describes this project very well 👍

**Comment by bajtos** [comment]
I am afraid this ship has already sailed, LoopBack is keeping the same name.
