### ISSUE TITLE
Authentication, what to expect.

### ISSUE THREAD

**Issue by dnmd** [strongloop/loopback-next#957]
From the [concept/feature mapping](http://loopback.io/doc/en/lb4/LoopBack-3.x.html#conceptfeature-mapping) (LB3/4) I noticed that for the authentication / authorization features, components will be used in LB4 ...

... and great work has already been done on the `@loopback/authentication` package.

However, authentication is hard to get right. In the current `@loopback/authentication` package Passport.js is used which is "just" authentication middleware, and does not handle any of the other parts of authentication, e.g. API / reset token mechanisms, etc.

Although the LB4 GA release is planned for next year, I am already very exited for its release 💯 ! But I do wonder what ideas / plans on the authentication / authorization part of LB4 lie ahead. What part of authentication / authorization do the developers need to "roll"? Or are there plans in the making, providing somewhat similar features as we know it in LB3?

**Comment by dhmlau** [comment]
@dnmd , thanks for your interest in LB4! 
@raymondfeng , could you please help in addressing the questions?  Thanks.

**Comment by kjdelisle** [comment]
pinging @raymondfeng

**Comment by bajtos** [comment]
This is a good question, @dnmd, and sorry for not responding earlier.

I am afraid we don't have a good answer yet. For now (4.0 GA), we are leaving authentication and authorization pretty much out of the scope of the core framework. In the future, we would like to let both us and the community to experiment with different approaches to auth & auth and see which approach turns out to be most usable/useful.
