### ISSUE TITLE
Add in tests for JSON Schemas being produced

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#971]
- JSON Schemas produced by `repository-json-schema` should be validated against this meta-schema (used to validate the schema itself): http://json-schema.org/schema. More information here: http://json-schema.org/specification.html#meta-schemas.

## Acceptance Criteria
- [ ] write tests for _types_ of JSON Schema in `repository-json-schema`
- [ ] validate JSON Schemas produced in the tests of `repository-json-schema` with a JSON-Schema-validating-JSON Schema

**Comment by virkt25** [comment]
A list of packages we can use for validation: 
http://json-schema.org/implementations.html#validator-javascript

**Comment by raymondfeng** [comment]
https://github.com/epoberezkin/ajv

**Comment by rahulrkr08** [comment]
https://github.com/hapijs/joi ??

**Comment by virkt25** [comment]
How is this different from #1294?

**Comment by shimks** [comment]
@virkt25 #1294 is adding in validation for the purpose of validating parameters parsed from http requests. This one will be used to validate whether the JSON Schemas our packages produce are themselves valid JSON Schemas. The reason we should have this validation should be congruent to the reason we have openapi-v3 spec validator.

**Comment by shimks** [comment]
Throwing back to have the acceptance criteria fleshed out: what is this extension geared towards? What is the UX? Is this an internal utility?

If internal: it should live in testlab, it should also be less restrictive

**Comment by bajtos** [comment]
> rovide a general validateJsonSchema function that returns a boolean based on whether the argument is a valid JSON Schema or not.

Returning a boolean is not helpful. When the document is not a valid JSON schema, then we need a descriptive list of spec violations, so that we know what to fix!

> what is this extension geared towards? What is the UX? Is this an internal utility?

To be honest, I don't know. What was your intention when you opened this issue?

As I am thinking about this, maybe what we really want is to write few unit tests for `repository-json-schema` to verify that we are producing a proper JSON schema documents. If that's the case, then I think this issue/story should be renamed to reflect this intention. I also may not need any publicly-exposed JSON-schema validator in testlab, we can simply set up the validator in `repository-json-schema` tests only.
